### ISSUE TITLE
Any chances for the tunnel allowing CCTV feed to be broadcast?

### ISSUE THREAD

**Issue by ranrinc** [brenner-tobias/addon-cloudflared#100]
Any chances for the tunnel allowing CCTV feed to be broadcast? If yes, do we need to add ingress into the setup?

**Comment by elcajon** [comment]
Should be possible as ingress setup is already implemented via `additional_hosts` configuration option. 
But you should pay attention to the Cloudflare usage agreement, take a look [here](https://github.com/brenner-tobias/addon-cloudflared#disclaimer).

**Comment by ranrinc** [comment]
> Should be possible as ingress setup is already implemented via `additional_hosts` configuration option. But you should pay attention to the Cloudflare usage agreement, take a look [here](https://github.com/brenner-tobias/addon-cloudflared#disclaimer).

I guess you are in the agreement part. :(
