### ISSUE TITLE
Tunnel name already exist

### ISSUE THREAD

**Issue by Bartek200219** [brenner-tobias/addon-cloudflared#107]
**Describe the bug**
After some use of this addon I got an error that tunnel already exist, so I added 't' at the end of the name in the config, then the problem went back, and I repeated it problem occurred one more time.

**To Reproduce**

1. Setup addon
2. Wait a few days
3. Check for error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/37016424/173153458-6518d603-2a0e-4be7-86b3-dbf5e2024ca3.png)
https://pastebin.com/trJzp8HW
**Add-On / Home Assistant Information (please complete the following information):**

Add-on version: 2.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.6  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2022.5.4
 Home Assistant Supervisor: 2022.05.3

**Comment by brenner-tobias** [comment]
Can you elaborate on the exact add-on config that you are using?

**Comment by brenner-tobias** [comment]
Might also be the same cause as #99
