### ISSUE TITLE
Can't delete Additional Hosts

### ISSUE THREAD

**Issue by antonio1475** [brenner-tobias/addon-cloudflared#110]
**Describe the bug**
When trying to delete all the additional hosts, I get:

> Failed to save add-on configuration, Missing option 'additional_hosts' in root in Cloudflared (90xxxxfa_cloudflared). Got {'external_hostname': 'axxxxxxxe.ga', 'tunnel_name': 'homeassistant', 'tunnel_token': ''}

I can only edit to make the additional host pointing nowhere.

**To Reproduce**

1. Go to Cloudflared Configuration tab
2. Delete all Additional Hosts
3. Save

**Expected behavior**
Configuration is saved without errors. Additional Hosts are removed

**Screenshots**
![image](https://user-images.githubusercontent.com/63130724/174070974-29d45d05-9fdf-4ab4-8b82-d1e2bd014c3e.png)
**Add-On / Home Assistant Information (please complete the following information):**

- Add-On Version (e.g. 0.7)
- Supervisor Version (e.g. supervisor-2021.10.8)
- Core Version (e.g. core-2021.11.5)
- Operating System (e.g. Home Assistant OS 6.6)
- Devices (e.g. Raspberry Pi 4 Model B)

**Additional context**

**Comment by elcajon** [comment]
Try to use the YAML editor to change the add-on config and make sure to add:
`additional_hosts: []`

**Comment by antonio1475** [comment]
Thank you. That works. I had tried like the empty tunnel but didn't work.
