### ISSUE TITLE
Couldn't connect to server

### ISSUE THREAD

**Issue by romanorac** [brenner-tobias/addon-cloudflared#111]
**Describe the bug**

I'm using the latest version of cloudflared: 2.0.2.

I followed the documentation and when I start cloudflared I get the following log output:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
curl: (7) Couldn't connect to server
[17:16:27] ERROR: Something went wrong contacting the API
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
curl: (7) Couldn't connect to server
[17:16:27] ERROR: Something went wrong contacting the API
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-cloudflared-log: starting
s6-rc: info: service init-cloudflared-log successfully started
s6-rc: info: service init-cloudflared-config: starting
[17:16:27] INFO: Checking Add-on config...
[17:16:27] FATAL: 'external_hostname' is empty, please enter a valid String
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service init-cloudflared-log: stopping
s6-rc: info: service init-cloudflared-log successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

I tried various configurations and I made sure external_hostname is filled, which in logs it says it is not. I always get the same error.

In configuration.yaml I also added 
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24`
```

- Add-On Version:  2.0.2.
- Supervisor Version (e.g. supervisor-2021.10.8): supervisor-2022.05.3
- Core Version (e.g. core-2021.11.5): core-2022.6.6
- Operating System (e.g. Home Assistant OS 6.6): Ubuntu 16.04.7 LTS 
- Devices (e.g. Raspberry Pi 4 Model B): HP laptop.

**Comment by elcajon** [comment]
Did you already try to uninstall and install the add-on? 

> `cont-init: info: running /etc/cont-init.d/00-banner.sh
curl: (7) Couldn't connect to server`

The line above indicates that the add-on is not able to access the supervisor, which allows explains why the add-on doesn't get the entered external_hostname value.

> `[17:16:27] FATAL: 'external_hostname' is empty, please enter a valid String`

The problem is that there seems to be something wrong with your supervisor which results in your add-on not able to communicate with HA backend API. Are all other add-ons working?

**Comment by romanorac** [comment]
I tried to reinstall it just now and I get the same error. I also rebooted the machine.

I use many addons and haven't had a problem with them. Here is a screenshot:

<img width="583" alt="Screenshot 2022-06-16 at 18 51 53" src="https://user-images.githubusercontent.com/8342728/174124789-8b059aa8-3285-4194-ad79-52a61ae8fc67.png">

Thanks for a fast reply.

**Comment by elcajon** [comment]
Seems to be an issue with your Installation method. Nothing we can do on our side.
This will occur with any image which issues the same base Image as we do (Hass Community addons alpine base 12.0.0)

**Comment by romanorac** [comment]
Do you mean: supervisor that is running in a docker on an ubuntu? 

What's is an alternative?

**Comment by elcajon** [comment]
Exactly. You are Running an Installation method which isn’t officially supported. I guess you run the supervised installation? If so then only debian (bullseye I assume) is supported. Have a look at the official instruction site to see the currently applicable requirements.

**Comment by romanorac** [comment]
Thank you for your help. Let me know if any other solution is available so that I don't have reinstall my system with debian.
