### ISSUE TITLE
Cloudflared 

### ISSUE THREAD

**Issue by skrilla0** [brenner-tobias/addon-cloudflared#116]
The CF Tunnel Add-On has been rock solid up until this point. Still running the old version 1.04 with Nginx Proxy Manager .11.0

From the mobile HA iOS app, I've been running into issues where I'm displayed with the following nginx error intermittently:

![HA](https://user-images.githubusercontent.com/89170690/176576043-9a488eb8-c680-4bd9-a4ba-96e52391f78e.png)

Sometimes this happens when I change connections from Wifi to mobile & occasionally just trying to access from outside of my home LAN.  To resolve, I'm, forced \to manually close the app, and reopen until it auto authenticates itself back into HA. 

Not sure if related, but in the Cloudflared logs, I'm consistently receiving this error: `If this log occurs persistently, and cloudflared is unable to connect to Cloudflare Network with `quic` protocol, then most likely your machine/network is getting its egress UDP to port 7844 (or others) blocked or dropped. Make sure to allow egress connectivity as per https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ports-and-ips/` 

Are these issues because I'm on the old version? Been reluctant to upgrade until this point because "it just works."

**Comment by skrilla0** [comment]
Please disregard. Think I figured it out.

**Comment by elcajon** [comment]
Would you like to share your solution if anything else got a similar problem with cloudflared tunnel and nginx proxy?

**Comment by skrilla0** [comment]
Tbh, it's user error. Rapidly disconnecting from Wifi to mobile, and having a privacy VPN enabled created the issue. Sorry for creating this case.
