### ISSUE TITLE
Availability on HA Core trough HACS

### ISSUE THREAD

**Issue by kimme1024** [brenner-tobias/addon-cloudflared#127]
**Is your feature request related to a problem? Please describe.**
As I'm stuck with HA Core in venv for my usecase I don't have access to the addon store.

**Describe the solution you'd like**
It would be great to be able to install your addon via HACS in HA Core to use this service.

**Describe alternatives you've considered**
Setting up a secure remote connection isn't that easy using my particular setup which causes some security issues.

**Additional context**
/

**Comment by elcajon** [comment]
This is a completely different technique. As far as I know it is not possible to start processes via integrations. If this is possible and someone knows about it, please reopen the incident. But this won't be part of this add-on.
