### ISSUE TITLE
Support of multiple domain name

### ISSUE THREAD

**Issue by kavierkoo** [brenner-tobias/addon-cloudflared#131]
Thanks Brenner Tobias for your awesome work to make the integration so so so easy.

I have 2 users that will be accessing Home Assistant.
Each of us have our own domain name.
example: ha.user1.com and ha.user2.com

But the AddOn only allows us to create 1 Cloudflared tunnel. (Please correct me if I'm wrong)

I have a NAS running cloudflared on docker, I am able to create multiple cloudflared docker to cater the different domain names.

Hence would like to check / request a feature to allow multiple domain name to be used to access via CloudFlare tunnel.

I am open for any suggestion to achieve above scenario. 
Appreciate your help and thank you in advance!

**Comment by elcajon** [comment]
Hey @kavierkoo, this is already possible thanks to the `additional_hosts` add-on option. Please have a look at the documentation and get back to us if anything isn't clear.

**Comment by kavierkoo** [comment]
Ah! That explains! No worries! I saw CloudFlare Argo supports it hence was trying to check if it is possible with this addon too!

Anyhoo thanks for all the efforts! Y'all rock!
