### ISSUE TITLE
Is it normal that the tunnel does not appear in the dashboard?

### ISSUE THREAD

**Issue by felipecrs** [brenner-tobias/addon-cloudflared#14]
This is more a question than anything else. I'm new to Cloudflare in general, but I wonder if the dashboard wasn't supposed to show the configured tunnel:

![image](https://user-images.githubusercontent.com/29582865/148771968-a0fadb56-92a9-494e-9ace-f0ab284a9d1f.png)

However, despite not showing up there, everything is working fine. Also, I can see the new entry under my DNS for the tunnel.

**Comment by brenner-tobias** [comment]
The tunnel should definitely show up there. I found that the UI is sometimes buggy, so try to reload the page a couple of times and it should be shown there.

**Comment by felipecrs** [comment]
I didn't have a Teams plan selected indeed. I selected the free plan, and indeed it shows up there:

![image](https://user-images.githubusercontent.com/29582865/148818059-89b3727c-dcb0-4ce4-92d2-994f5334e1fb.png)

Thank you!
