### ISSUE TITLE
Fallback to config when Tunnel Token Invalid?

### ISSUE THREAD

**Issue by cortado** [brenner-tobias/addon-cloudflared#142]
Having problem that a remote installation stopped connecting after error with tunnel token.: "Tunnel token not valid".

Running HASSIO on RPI3b, pretty much vanilla and latest version everything. 

I might have copy/pasted the wrong one or I rolled it. Anyway, that means I cannot access my HA instance, since by entering tunnel token in config, other config parameters are not used. I have not found a way to edit addon config via HA CLI commands (which I can access), so my remote location is only accessible by plane, and 2 hour drive... 

If there was a fallback to other config because for some reason an API tunnel token became invalid, or wrong, would dit not be good to have a fallback, or maybe a choice to activate such a fallback? 

Or is there maybe a way to edit config via SSH and CLI, which of course is preferred if the roll is related to security breach?

**Comment by elcajon** [comment]
We cannot catch every user error from add-on side. Also, for the locally configured tunnel, a second Cloudflare tunnel would be needed, which would result in all DNS entries having to be changed. This would not work and I don't see this in the scope of this add-on at the moment.

As for your specific problem, I see several possibilities. If your access via cli still works you could install the SSH add-on and start a Cloudflare tunnel there, alternatively you could also install the Tailscale add-on and access the GUI via the VPN connection. These are just two possibilities, certainly there are other alternatives.

**Comment by cortado** [comment]
Great, thanks – was just a thought, but as I understand it, not a very good one. 

I have access to SSH via PiTunnel on a second RPi. that is how I access CLI, via SSH addon. My only problem now is to get a tunnel started – that is to say enter some config to access my Cloudflare tunnel. Any advice on either how to edit config files directly to remove the Tunnel Token and restart addon, or to manually start a tunnel via terminal with the right settings?

**Comment by elcajon** [comment]
I guess that it isn't possible to change add-on options from ha cli side. 

Follow these steps to spin up cloudflared inside SSH add-on, adapt URL if you don't use RPI with arm64
```
curl -fsSL --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/download/2022.8.0/cloudflared-linux-arm64.deb
dpkg -i cloudflared.deb 
cloudflared tunnel run --token="<enter correct token here 😉>"
```

**Comment by cortado** [comment]
> 

YESSS thank you, the shell file approach worked!!! You just saved me 6 hours travel and airfare!

**Comment by elcajon** [comment]
Perfect, I would sugest to implement a fallback option like Tailscale or Wireguard so you can access the GUI if cloudflare fails for some reason.
