### ISSUE TITLE
Add-on shuts down after Internet outage.

### ISSUE THREAD

**Issue by ashwinikalantri** [brenner-tobias/addon-cloudflared#146]
Before the 2.0.7 release, after an Internet outage, the add on would have to be restarted manually to re establish the tunnel (#139). This was fixed, but now the add-on shuts down and needs to be started. I have watchdog turned on, but it fails to start the add-on.

**Comment by ashwinikalantri** [comment]
Logs:

> [19:43:56] WARNING: Connection attempt 10/24 before restart.
> 2022-08-14T14:13:57Z ERR Unable to establish connection with Cloudflare edge error="DialContext error: dial tcp 198.41.200.33:7844: i/o timeout" connIndex=0 ip=198.41.200.33
> 2022-08-14T14:13:57Z ERR Serve tunnel error error="DialContext error: dial tcp 198.41.200.33:7844: i/o timeout" connIndex=0 ip=198.41.200.33
> 2022-08-14T14:13:57Z INF Retrying connection in up to 1s seconds connIndex=0 ip=198.41.200.33
> [19:44:01] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:01] WARNING: Connection attempt 11/24 before restart.
> [19:44:06] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:06] WARNING: Connection attempt 12/24 before restart.
> [19:44:11] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:11] WARNING: Connection attempt 13/24 before restart.
> 2022-08-14T14:14:13Z ERR Unable to establish connection with Cloudflare edge error="DialContext error: dial tcp 198.41.200.33:7844: i/o timeout" connIndex=0 ip=198.41.200.33
> 2022-08-14T14:14:13Z ERR Serve tunnel error error="DialContext error: dial tcp 198.41.200.33:7844: i/o timeout" connIndex=0 ip=198.41.200.33
> 2022-08-14T14:14:13Z INF Retrying connection in up to 4s seconds connIndex=0 ip=198.41.200.33
> [19:44:16] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:16] WARNING: Connection attempt 14/24 before restart.
> [19:44:21] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:21] WARNING: Connection attempt 15/24 before restart.
> [19:44:26] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:26] WARNING: Connection attempt 16/24 before restart.
> 2022-08-14T14:14:31Z ERR Unable to establish connection with Cloudflare edge error="DialContext error: dial tcp 198.41.200.33:7844: i/o timeout" connIndex=0 ip=198.41.200.33
> 2022-08-14T14:14:31Z ERR Serve tunnel error error="DialContext error: dial tcp 198.41.200.33:7844: i/o timeout" connIndex=0 ip=198.41.200.33
> 2022-08-14T14:14:31Z INF Retrying connection in up to 8s seconds connIndex=0 ip=198.41.200.33
> [19:44:31] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:31] WARNING: Connection attempt 17/24 before restart.
> [19:44:36] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:36] WARNING: Connection attempt 18/24 before restart.
> [19:44:41] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:41] WARNING: Connection attempt 19/24 before restart.
> [19:44:46] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:46] WARNING: Connection attempt 20/24 before restart.
> 2022-08-14T14:14:50Z ERR Unable to establish connection with Cloudflare edge error="DialContext error: dial tcp 198.41.200.33:7844: i/o timeout" connIndex=0 ip=198.41.200.33
> 2022-08-14T14:14:50Z ERR Serve tunnel error error="DialContext error: dial tcp 198.41.200.33:7844: i/o timeout" connIndex=0 ip=198.41.200.33
> 2022-08-14T14:14:50Z INF Retrying connection in up to 16s seconds connIndex=0 ip=198.41.200.33
> [19:44:51] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:51] WARNING: Connection attempt 21/24 before restart.
> [19:44:56] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:44:56] WARNING: Connection attempt 22/24 before restart.
> [19:45:01] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:45:01] WARNING: Connection attempt 23/24 before restart.
> [19:45:06] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:45:06] WARNING: Connection attempt 24/24 before restart.
> [19:45:06] ERROR: Restarting Cloudflared service
> 2022-08-14T14:15:06Z INF Initiating graceful shutdown due to signal terminated ...
> 2022-08-14T14:15:06Z INF Tunnel server stopped
> 2022-08-14T14:15:06Z ERR Unable to establish connection with Cloudflare edge error="DialContext error: dial tcp 198.41.200.33:7844: operation was canceled" connIndex=0 ip=198.41.200.33
> 2022-08-14T14:15:06Z ERR Serve tunnel error error="DialContext error: dial tcp 198.41.200.33:7844: operation was canceled" connIndex=0 ip=198.41.200.33
> 2022-08-14T14:15:06Z INF Metrics server stopped
> [19:45:06] INFO: cloudflared stoped, restarting...
> [19:45:07] INFO: Connecting Cloudflared Tunnel...
> 2022-08-14T14:15:07Z INF Starting tunnel tunnelID=xxxxxxxxxx
> 2022-08-14T14:15:07Z INF Version 2022.7.1
> 2022-08-14T14:15:07Z INF GOOS: linux, GOVersion: go1.17.10, GoArch: amd64
> 2022-08-14T14:15:07Z INF Settings: map[config:/tmp/config.json cred-file:/data/tunnel.json credentials-file:/data/tunnel.json loglevel:info metrics:localhost:36500 no-autoupdate:true origincert:/data/cert.pem]
> 2022-08-14T14:15:07Z INF Generated Connector ID: xxxxxxxxxx
> 2022-08-14T14:15:17Z ERR update check failed error="Get \"https://update.argotunnel.com?arch=amd64&clientVersion=2022.7.1&os=linux\": dial tcp: lookup update.argotunnel.com on 127.0.0.11:53: read udp 127.0.0.1:38691->127.0.0.11:53: i/o timeout"
> 2022-08-14T14:15:17Z ERR Unable to lookup protocol. Defaulting to `http2`. If this fails, you can set `--protocol h2mux` in your cloudflared command. error="lookup protocol-v2.argotunnel.com on 127.0.0.11:53: server misbehaving"
> 2022-08-14T14:15:17Z INF Initial protocol http2
> 2022-08-14T14:15:17Z INF Starting metrics server on 127.0.0.1:36500/metrics
> [19:45:17] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:45:17] WARNING: Connection attempt 1/24 before restart.
> [19:45:22] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:45:22] WARNING: Connection attempt 2/24 before restart.
> [19:45:27] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:45:27] WARNING: Connection attempt 3/24 before restart.
> [19:45:32] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:45:32] WARNING: Connection attempt 4/24 before restart.
> [19:45:37] WARNING: Connection unavailable, rechecking in 5 seconds.
> [19:45:37] WARNING: Connection attempt 5/24 before restart.
> 2022-08-14T14:15:42Z ERR Error looking up Cloudflare edge IPs: the DNS query failed error="lookup _v2-origintunneld._tcp.argotunnel.com on 127.0.0.11:53: server misbehaving"
> 2022-08-14T14:15:42Z ERR Please try the following things to diagnose this issue:
> 2022-08-14T14:15:42Z ERR   1. ensure that argotunnel.com is returning "origintunneld" service records.
> 2022-08-14T14:15:42Z ERR      Run your system's equivalent of: dig srv _origintunneld._tcp.argotunnel.com
> 2022-08-14T14:15:42Z ERR   2. ensure that your DNS resolver is not returning compressed SRV records.
> 2022-08-14T14:15:42Z ERR      See GitHub issue https://github.com/golang/go/issues/27546
> 2022-08-14T14:15:42Z ERR      For example, you could use Cloudflare's 1.1.1.1 as your resolver:
> 2022-08-14T14:15:42Z ERR      https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/
> 2022-08-14T14:15:42Z INF Tunnel server stopped
> 2022-08-14T14:15:42Z ERR Initiating shutdown error="Could not lookup srv records on _v2-origintunneld._tcp.argotunnel.com: lookup _v2-origintunneld._tcp.argotunnel.com on 127.0.0.11:53: server misbehaving"
> 2022-08-14T14:15:42Z INF Metrics server stopped
> Could not lookup srv records on _v2-origintunneld._tcp.argotunnel.com: lookup _v2-origintunneld._tcp.argotunnel.com on 127.0.0.11:53: server misbehaving
> [19:45:42] WARNING: cloudflared crashed, halting add-on
> [19:45:42] INFO: cloudflared stoped, restarting...
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service healthcheck: stopping
> [19:45:42] INFO: healthcheck stoped, restarting...
> s6-rc: info: service healthcheck successfully stopped
> s6-rc: info: service cloudflared: stopping
> [19:45:42] INFO: cloudflared stoped, restarting...
> s6-rc: info: service cloudflared successfully stopped
> s6-rc: info: service init-cloudflared-config: stopping
> s6-rc: info: service init-cloudflared-config successfully stopped
> s6-rc: info: service init-cloudflared-log: stopping
> s6-rc: info: service init-cloudflared-log successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by elcajon** [comment]
#147 should fix the wrong watchdog behavior

**Comment by ashwinikalantri** [comment]
The add-on continues to crash and not restart even with watchdog after internet outage.

**Comment by ashwinikalantri** [comment]
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflared tunnel (formerly Argo Tunnel) to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 2.0.12
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.4  (amd64 / qemux86-64)
 Home Assistant Core: 2022.8.5
 Home Assistant Supervisor: 2022.08.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-cloudflared-log: starting
s6-rc: info: service init-cloudflared-log successfully started
s6-rc: info: service init-cloudflared-config: starting
[17:13:55] INFO: Checking Add-on config...
[17:13:56] INFO: Checking for existing certificate...
[17:13:56] INFO: Existing certificate found
[17:13:56] INFO: Checking for existing tunnel...
[17:13:56] INFO: Existing tunnel with ID xxxxx found
[17:13:56] INFO: Checking if existing tunnel matches name given in config
REST request failed: Get "https://api.cloudflare.com/client/v4/accounts/1728f94xxxxxxxxx7185a/cfd_tunnel?is_deleted=false&uuid=23f36xxxxxbcf11bf": dial tcp: lookup api.cloudflare.com on 127.0.0.11:53: read udp 127.0.0.1:48570->127.0.0.11:53: i/o timeout
[17:14:06] ERROR: Existing Cloudflare tunnel name does not match add-on config.
[17:14:06] ERROR: ---------------------------------------
[17:14:06] ERROR: Add-on Configuration tunnel name: ha158
[17:14:06] ERROR: Tunnel credentials file tunnel name: 
[17:14:06] ERROR: ---------------------------------------
[17:14:06] ERROR: Align add-on configuration to match existing tunnel credential file
[17:14:06] ERROR: or reset the add-on. Take a look at the documentation on how to reset the add-on
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service init-cloudflared-log: stopping
s6-rc: info: service init-cloudflared-log successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by elcajon** [comment]
> REST request failed: Get "https://api.cloudflare.com/client/v4/accounts/1728f94xxxxxxxxx7185a/cfd_tunnel?is_deleted=false&uuid=23f36xxxxxbcf11bf": dial tcp: lookup api.cloudflare.com on 127.0.0.11:53: read udp 127.0.0.1:48570->127.0.0.11:53: i/o timeout

I guess this is because your connection still isn't available, correct? 

@brenner-tobias I hardly could find any information on how the watchdog is supposed to work expect [this blog post](https://www.home-assistant.io/blog/2020/09/16/supervisor-joins-the-party/#improve-add-on-availability-with-the-new-watchdog-feature). As far as I understand, the add-on should restart no matter why it stops (by error or clean shutdown). I start to wonder if this could be an upstream supervisor problem, maybe we should open an issue. What do you think?

**Comment by ashwinikalantri** [comment]
My internet went out at about 17:10. Service shut down after about 5 minutes. Is that expected behaviour?

Shouldn't the add-on keep checking for internet and reconnect when it is available.

**Comment by brenner-tobias** [comment]
@elcajon I think we have to raise this at the supervisor level. I recently had a longer internet outage and after the connection was restored, HA did not manage to realize that it was back (e.g. my Netatmo connection was not coming back). Only after a restart of HA everything worked again.

**Comment by elcajon** [comment]
Do you have logs from that time that could be attached in an issue? Otherwise we would have to stimulate the behavior again and unplug the Ethernet cable for a while. I am currently not sure if this is an OS or supervisor or DNS container issue.

**Comment by elcajon** [comment]
I've checked the supervisor logs after disconnecting the network connection for my HA VM for about half a hour.
The problem is that there is a threshold of 10 restarts in 30 min configured in supervisor for add-ons watchdog.

To get around this #164 implements a internet check at the start of the cloudflare-init script, so the add-on won't start without internet connection and therefore won't be killed by watchdog or our implemented healthcheck.

<img width="1076" alt="Bildschirmfoto 2022-08-21 um 16 09 30" src="https://user-images.githubusercontent.com/52052494/185798146-f1e0083f-2243-438b-84ec-1f1adc3601b8.png">

**Comment by elcajon** [comment]
@ashwinikalantri feel free to try the new version on the [edge repository](https://github.com/brenner-tobias/ha-addons-edge)

**Comment by ashwinikalantri** [comment]
Luckily I haven't had an internet outage since past few days. Will keep an eye and update if any issue persists.

**Comment by ashwinikalantri** [comment]
I had my internet go down a few times over the past few days. The add-on didn't crash on version 2.0.13, 2.0.14 or 2.0.15.
