### ISSUE TITLE
Add timestamps to log output?

### ISSUE THREAD

**Issue by grahamkennery** [brenner-tobias/addon-cloudflared#148]
**Is your feature request related to a problem? Please describe.**
Currently the log does not provide timestamps for startup/normal operation. I'd like to know if the addon crashed/restarted and can't tell the difference between the addon working for a few days vs restarting silently 

**Describe the solution you'd like**
Timestamps on logs when viewed in the Home Assistant dashboard

**Describe alternatives you've considered**

**Additional context**
![Screenshot_20220814-162715.png](https://user-images.githubusercontent.com/2604414/184553736-fd2f1bf8-9b91-4fc6-89f0-62bc61e3bac0.png)

**Comment by elcajon** [comment]
We use the standard log output provided by the Community Add-Ons framework, this is because the base image is also used by HA Community Add-Ons. Unfortunately we have no influence on the log entries. 
However, the entries after your screenshot "INFO:" are all provided with a time.
