### ISSUE TITLE
Add-on keeps restarting every few minutes 

### ISSUE THREAD

**Issue by crhass** [brenner-tobias/addon-cloudflared#149]
### The problem

The add-on keeps restarting. 
The supervisor logs in home assistant show watchdog problems.

### What version of Cloudflared has the issue?

2.0.8

### What was the last working version of Cloudflared?

2.0.7

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
additional_hosts: []
external_hostname: hidden.co.uk
tunnel_name: hidden
tunnel_token: ""
warp_enable: false
```

### Anything in the logs that might be useful for us?

```txt
22-08-14 21:38:30 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 9074a9fa_cloudflared
22-08-14 21:40:30 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 9074a9fa_cloudflared application!
22-08-14 21:40:30 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping addon_9074a9fa_cloudflared application
22-08-14 21:40:36 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_9074a9fa_cloudflared application
22-08-14 21:40:38 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on ghcr.io/brenner-tobias/cloudflared/armv7 with version 2.0.8
22-08-14 21:40:49 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from 9074a9fa_cloudflared
22-08-14 21:42:38 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 9074a9fa_cloudflared
22-08-14 21:44:38 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 9074a9fa_cloudflared application!
```

### Steps to reproduce the issue

Install and configure 2.0.7
Turn on watchdog
Upgrade to 2.0.8

**Comment by jklimek** [comment]
Having the same issue after updating.
Also some warnings from Cloudflared logs after restart:

`2022-08-14T22:52:24Z INF Version 2022.8.0
2022-08-14T22:52:24Z INF GOOS: linux, GOVersion: go1.18, GoArch: amd64
2022-08-14T22:52:24Z INF Settings: map[config:/tmp/config.json cred-file:/data/tunnel.json credentials-file:/data/tunnel.json loglevel:info metrics:localhost:36500 no-autoupdate:true origincert:/data/cert.pem]
2022-08-14T22:52:24Z INF Generated Connector ID: c8d8cb00-**********************
2022-08-14T22:52:24Z INF Initial protocol quic
2022-08-14T22:52:24Z INF Starting metrics server on 127.0.0.1:36500/metrics
[00:52:24] WARNING: Connection unavailable, rechecking in 5 seconds.
[00:52:24] WARNING: Connection attempt 1/24 before restart.
2022-08-14T22:52:25Z INF Connection ca7d8c67-34b9-433b-b6c8-2457a3726f15 registered connIndex=0 ip=198.41.***.** location=***`

**Comment by elcajon** [comment]
I am already looking at this, until a solution is provided best to disable Watchdog.

**Comment by irqnet** [comment]
I don't have any more details that would help troubleshooting, but I can confirm that it works with version 2.0.7 and since the update to 2.0.8 no longer.

I maintain another installation that is still running on 2.0.7, there is not the problem.
