### ISSUE TITLE
Question on new domain setup through cloudflare

### ISSUE THREAD

**Issue by jcat59** [brenner-tobias/addon-cloudflared#15]
Hi and thanks so much for your work on creating this application. I was able to successfully implement after setting up a new domain on cloudflare, and it works great!!

Couple questions:
1. Are you planning to set this up through the HA Community Addons?
2. As far as nginxproxymanager - do you use it?
3. Is there anything else you'd recommend for security, besides 2FA?
4. Finally - what did you use to create your webpage :)

Thanks again for sharing your work! As an FYI - Currently I have HA OS running on a RPI4..

**Comment by brenner-tobias** [comment]
Thanks for your issue, see my comment below:

1. Yes, but they are currently not accepting any new add-ons
2. Yes, I use it for one of my installations. I am currently working on a new version of this add-on though, which will enable the use of multiple hosts (so an included reverse proxy). After that, there is no need for NPM (at least for me). I will still leave the option for NPM in there though
3. I recommend going into the Cloudflare Teams dashboard and create an application (self hosted application with your ha domain). You can then implement GitHub as login so you will have another layer of security. See [here](https://developers.cloudflare.com/cloudflare-one/applications/configure-apps/self-hosted-apps) for more details.
4. Plain and simple Bootstrap 5, hand coded 

Thanks for using the add-on!
