### ISSUE TITLE
addon fails to start

### ISSUE THREAD

**Issue by brozorb** [brenner-tobias/addon-cloudflared#163]
### The problem

after update the addon will not start and says that a tunnel with the same name already exists
![image](https://user-images.githubusercontent.com/84518177/185762585-efe2d249-0b23-4094-b400-a9bc135abeb4.png)

### What version of Cloudflared has the issue?

2.0.12 

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
additional_hosts: []
external_hostname: my.domain.tld
tunnel_name: homeassistant
tunnel_token: ""
```

### Anything in the logs that might be useful for us?

```txt
s6-rc: info: service init-cloudflared-log successfully started 
s6-rc: info: service init-cloudflared-config: starting 
[12:42:43] INFO: Checking Add-on config... 
[12:42:45] INFO: Checking for existing certificate... 
[12:42:45] INFO: Existing certificate found 
[12:42:45] INFO: Checking for existing tunnel... 
[12:42:45 ] NOTICE: No tunnel file found 
[12:42:45] INFO: Creating new tunnel... failed to create tunnel: Create Tunnel API call failed: tunnel with name already exists [12:42:45] FATAL: Failed to create tunnel.
Please check the Cloudflare Teams Dashboard for an existing tunnel with the name homeassistant and delete it:
https://dash.teams.cloudflare.com/ Access / Tunnels 
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1 /run/s6/basedir/scripts/rc.init: warning: 
s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaughtlogs/current if you have in-container logging) for more information. prog: fatal: stopping the container. 
s6-rc: info: service init-cloudflared-log: stopping 
s6-rc: info: service init-cloudflared-log successfully stopped 
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped 
s6-rc: info: service fix-attrs: stopping 
s6-rc: info: service fix-attrs successfully stopped 
56-rc: info: service src-oneshot-runner: stopping 
56-rc: info: service src-oneshot-runner successfully stopped
```

### Steps to reproduce the issue

update to latest version and start addon

### Additional information

can be fixed by changing the tunnel name in the config

EDIT: put newlines in logs

**Comment by brenner-tobias** [comment]
Looks like you lost your tunnel file during the update. Which version did you update from?
Also, please try to delete the tunnel in Cloudflare and recreate it. Then check, if this happens again during normal runtime or after an update.

**Comment by brozorb** [comment]
I'm not entirely sure which version I updated from but looking at release dates it's probably 2.0.4.
I can't delete the tunnel from the dashboard because I haven't selected a tier yet as it requires payment info even for free tier. I will check next update if it still breaks.

**Comment by isorensen** [comment]
Same for me. I try to start it, and it gives me this message bellow. And I still haven't figured out how to fix it.

![image](https://user-images.githubusercontent.com/3399976/185809084-c416446e-bdb8-484c-81eb-84d5e9741c13.png)

**Comment by isorensen** [comment]
Hey @brozorb , I was able to delete the last tunnel by chosing the "Free Plan". I actually had to add my credit card, but it was a "zero dollar purchase".
After deleting it, Cloudflared was able to start again in HAOS.

**Comment by djfeld01** [comment]
> Same for me. I try to start it, and it gives me this message bellow. And I still haven't figured out how to fix it.
> 
> ![image](https://user-images.githubusercontent.com/3399976/185809084-c416446e-bdb8-484c-81eb-84d5e9741c13.png)

![iScreen Shoter - 20220822074006548](https://user-images.githubusercontent.com/75047623/185912895-f7f9ff78-0e99-4b23-9a96-c348b45d396f.jpg)

I'm having this issue as well.

**Comment by brenner-tobias** [comment]
this is very strange. Can you do delete the add-on repository from HA, restart HA, then add the repository again and try?
If this is not working: Try adding the edge-repository: https://github.com/brenner-tobias/ha-addons-edge since this has worked for someone else who had this problem, though I have no idea why...

**Comment by djfeld01** [comment]
Now I'm not able to install them.  I'm going to reboot the system and try again, but this was the error I got on the Install step.

![iScreen Shoter - 20220822093728893](https://user-images.githubusercontent.com/75047623/185934819-07a5b1ba-1fb7-4661-8ea2-85d49c45d3dd.jpg)

**Comment by brozorb** [comment]
Just updated to 2.0.13 and it still works!

**Comment by isorensen** [comment]
Just updated to 2.0.13, and it stopped working. Now, with this message below. Anyone? And yes, my host (Raspberry Pi 4) is online with internet.

![image](https://user-images.githubusercontent.com/3399976/186024733-7bc99185-3745-4921-9813-cedb359bf992.png)

**Comment by elcajon** [comment]
We shouldn't mix up problems in one issue. 

> Just updated to 2.0.13 and it still works!

As the original problem was solved please open a new issue if anything else is not working for you.

**Comment by brozorb** [comment]
Yeah sorry I forgot to close it when it worked 😬
