### ISSUE TITLE
"CNAME not supported" error when using tunnel token

### ISSUE THREAD

**Issue by cortado** [brenner-tobias/addon-cloudflared#165]
### The problem

Log error in system log, but Addon keeps on running, so not an urgent problem. Something I should do, or that needs to be fixed?

### What version of Cloudflared has the issue?

2.0.13

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.cloudflare
Source: components/cloudflare/__init__.py:50 
Integration: Cloudflare (documentation, issues) 
First occurred: 22. august 2022, 13:20:55 (22 occurrences) 
Last logged: 10:20:57

Error updating zone XXXXXX.com: Record type CNAME, is not supported
```

### Steps to reproduce the issue

Using simple setup with only tunnel token in config. rest is vanilla HA on RPi

**Comment by elcajon** [comment]
That Home Assistant log message doesn't have anything in common with this add-on.
