### ISSUE TITLE
no internet connection

### ISSUE THREAD

**Issue by zakolg** [brenner-tobias/addon-cloudflared#170]
### The problem

I am currently running into an issue where the tunneling using freenom and cloudflared addon is seeming to not have an internet connection.

### What version of Cloudflared has the issue?

2.0.14

### What was the last working version of Cloudflared?

2.0.13

### What type of installation are you running?

Home Assistant Supervised

### Steps to reproduce the issue

Install cloudflare add-on, configure and run.

### Additional information

Add-on: Cloudflared
 Use a Cloudflared tunnel (formerly Argo Tunnel) to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 2.0.14
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 11 (bullseye)  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.8.7
 Home Assistant Supervisor: 2022.08.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-cloudflared-log: starting
s6-rc: info: service init-cloudflared-log successfully started
s6-rc: info: service init-cloudflared-config: starting
[20:41:10] ERROR: Host has no internet connection, waiting 30 seconds...

Ping from host cloudflare:
root@9074a9fa-cloudflared:/$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=55 time=25.378 ms
64 bytes from 1.1.1.1: seq=1 ttl=55 time=25.168 ms
64 bytes from 1.1.1.1: seq=3 ttl=55 time=27.396 ms

root@9074a9fa-cloudflared:/$ ping google.com
PING google.com (142.250.203.142): 56 data bytes
64 bytes from 142.250.203.142: seq=0 ttl=119 time=11.377 ms
64 bytes from 142.250.203.142: seq=1 ttl=119 time=12.942 ms
64 bytes from 142.250.203.142: seq=2 ttl=119 time=12.599 ms

**Comment by brenner-tobias** [comment]
Please try the current edge implementation. With the new Cloudflared version, we were able to remove our own internet check, which causes your error. Please keep in mind that this development is still ongoing, but we do have a first version in the Edge repository

**Comment by brenner-tobias** [comment]
I also just released 2.0.15 which also includes the fix.
