### ISSUE TITLE
Getting 400: Bad Request despite configuration.yaml set correctly

### ISSUE THREAD

**Issue by Moustik2002** [brenner-tobias/addon-cloudflared#175]
### The problem

I've tried to set up back my cloudflared addon with the last build 2.0.16

I've encountered some configration missmatch since the last time i've set it so i get back to cloudflare tunnel which has moved to recover my tocken and configure it correctly. Then i've managed to edit public network acoordingly and make sure the following lines are present in my configuration.yaml :

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

Unfortunately i'm stucking to this 400: Bad Request despite all my effort to fix it.
So i wonder if there was some change regarding ip range to full fill for trsuted_proxies perharps.
Bottom line i'm kinda lost

### What version of Cloudflared has the issue?

2.0.16

### What type of installation are you running?

Home Assistant Supervised

### Add-on YAML Configuration

```yaml
additional_hosts: []
external_hostname: mywebsite
tunnel_name: homeassistant
tunnel_token: >-
xxxxxxx
```

### Anything in the logs that might be useful for us?

```txt
ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp 127.0.0.1:8123: connect: connection refused" cfRay=748274b13b01d61d-CDG ingressRule=0 originService=http://localhost:8123
```

### Steps to reproduce the issue

nothing to add about what i've written in the the problem field

### Additional information

pardon my english i'm french

**Comment by elcajon** [comment]
```
ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp 127.0.0.1:8123: connect: connection refused" cfRay=748274b13b01d61d-CDG ingressRule=0 originService=http://localhost:8123
```

Did you configure your tunnel to route HA traffic from `http://localhost:8123` ? 
Depending on your supervised installation configuration you could try using `http://homeassistant:8123`.

e.g.:

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/52052494/189480545-b1eddce8-70e5-4832-8e2c-07193ebf1478.png">

**Comment by Moustik2002** [comment]
Thx for the feedback. i was setting pulbic hostname w/ my public IP. Now with the settings homeassistant:8123 and a proper edit of my etc/hosts it works !

Thank you very much !
