### ISSUE TITLE
Problem connect from Google Cloud

### ISSUE THREAD

**Issue by Gugulator** [brenner-tobias/addon-cloudflared#176]
### The problem

Using this addon
Everything works perfectly.
The question is how to add Google Home support now?

I do everything according to all the manuals.
At the stage, when you need to add a third -party service on the phone, I see my application created in Google Cloud.
When pressing it, the HA Authorization window opens.
After entering username and password for Home Assistant, Google Home gives an error that it cannot connect.

The following error appears in the Google Cloud logs:

  "Jsonpayload": {
    "Response": {
      **"Body": "404: Not Found",
      "Status": 404**
    },
    "@Type": "Type.googleapis.com/google.identity.accountlinking.type.accountlinkingeroror",
    "Errorreason": "**CAN'T PARSE the Response. The Response Needs to Be Json Format**.",

I suspect that this is somehow belongs to the tunnel.
I will be glad to hints what and where in Clodflare can be changed so that it will work.
WAF and all other things have already tried to turn off - it did not help.

### What version of Cloudflared has the issue?

2.0.16

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
add-on works perfectly
```

### Steps to reproduce the issue

try to config Google Assistant according to manual
https://www.home-assistant.io/integrations/google_assistant/

**Comment by brenner-tobias** [comment]
I do not use Google Assistant myself, but there were some [discussions in my initial thread about integrations like Alexa and Google](https://community.home-assistant.io/t/new-add-on-cloudflared/361637/72), so maybe you can find something there.
Also, some people reported that when using a free domain from freenom, these add-ons would not work. So what are you using?

**Comment by Gugulator** [comment]
Thank you for your answer.
I'm using paid domain name from other registrar, not from freenom.
I also will check the theead

**Comment by Gugulator** [comment]
Error Body": "404: Not Found",
"Status": 404 - was solved. I forgot to update new domain name in HA config. So after fix it thisproblem fixed.
The second problem still exists.
CAN'T PARSE the Response. The Response Needs to Be Json Format.",
Still looking for solution.

The other question about tunnel is - can I use certificate generated by cloudflare in my HA config? I see that current certificate for external domain name refreshing every restart of HA and given by different authorities for 3 months.

**Comment by brenner-tobias** [comment]
I am sorry but I am not using Google Assistant myself. I suggest again to post in the thread in the HA community, there are some people who might be able to help.
Regarding your HA config: I am not sure why you need the cloudflare certificate in the HA config. It will definitely not be valid if you are connecting via https in your local network using the IP of HA.
