### ISSUE TITLE
Add On not working after 0.2.1 update

### ISSUE THREAD

**Issue by jcat59** [brenner-tobias/addon-cloudflared#18]
Reverted back to 0.1.9 and it's working fine. Any idea what might be going wrong? I'd have to update again to get more detail on logs, but I appeared to be getting messages about unregistered web hooks.

**Comment by brenner-tobias** [comment]
Yes, I messed up, sorry.
I renamed a property in the config file, so a manual step would have been necessary after the update. When I realised that, I decided that the renaming was not that important and released 0.2.2 with the old naming, which should work fine.

Can you update and let me know?

**Comment by jcat59** [comment]
Updated again and still not working. Perhaps I updated to quick? Should I revert again? Or can you push with a new version number?

**Comment by brenner-tobias** [comment]
Did you update to 0.2.2 or was v0.2.1 still shown?

**Comment by jcat59** [comment]
0.2.1 was still shown

**Comment by brenner-tobias** [comment]
yeah then you have to revert and wait some time until 0.2.2 is shown.
Then you can update again.

**Comment by jcat59** [comment]
Ok perfect, I'll do that, thanks!

**Comment by jcat59** [comment]
Updated to 0.2.2, everything is working well. Thanks
