### ISSUE TITLE
Addon doesnt start anymore

### ISSUE THREAD

**Issue by evharten** [brenner-tobias/addon-cloudflared#233]
### The problem

Error: Image ghcr.io/brenner-tobias/cloudflared/amd64:4.0.2 does not exist for addon_9074a9fa_cloudflared

### What version of Cloudflared has the issue?

4.0.2

### What was the last working version of Cloudflared?

4.0.1

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Start 4.0.2 in Homeassistant.

**Comment by rzv-trsc** [comment]
had no problem with it; however was previously 4.0 and needed to reset/delete the tunnel so I uninstalled the addon and then rebuilt anything on a fresh install of the addon; may try that.

**Comment by evharten** [comment]
Deleting the addon, and reactivating it solved it, somehow something hangs it seems.
