### ISSUE TITLE
is this missing from doc?

### ISSUE THREAD

**Issue by Santanachia** [brenner-tobias/addon-cloudflared#260]
### The problem

I did not find in the documentation written explicitly not to specify the port in the browser.
I struggled for a long time with no connection because I only changed the address and not deleted the port.

### What version of Cloudflared has the issue?

404

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

open documentation

**Comment by brenner-tobias** [comment]
thanks for raising and you are right, this is not explicitly stated in the docs. @AlecRust do you think you can make a suggestion here? Otherwise I am happy to do so next week.

**Comment by AlecRust** [comment]
@Santanachia would the changes in #261 have helped to avoid this issue?

**Comment by Santanachia** [comment]
@AlecRust i don't see there the information that to connect to HA via domain you should stop using the port number.
on the local network I connect through homeassistant.local:8123, so from the external network I will also try to connect through ha.example.com:8123 and it will fail. I need to remove `:8123`.

**Comment by Santanachia** [comment]
I think a more complete description would be:
> Access your Home Assistant via the remote URL e.g. https://ha.example.com/ (without specifying the port number)

**Comment by AlecRust** [comment]
Thanks @Santanachia I've tweaked based on your feedback.

**Comment by brenner-tobias** [comment]
Thank you both very much, I just merged the changes in, they will be part of the next release.

**Comment by Santanachia** [comment]
@brenner-tobias i don't see my last suggestion in the merge :/

**Comment by AlecRust** [comment]
"Without port" is now in the instructions.

**Comment by Santanachia** [comment]
Thx
