### ISSUE TITLE
Local tunnel not reconnecting after update

### ISSUE THREAD

**Issue by brenner-tobias** [brenner-tobias/addon-cloudflared#276]
### The problem

My local test-system with local config does not reconnect after the update to 4.0.6. The local test-system with the remote managed tunnel is working fine.
Unfortunately, I do not currently have local access to the system, so I cannot check the logs.

@elcajon any chance you could have a quick look?

### What version of Cloudflared has the issue?

4.0.6

### What was the last working version of Cloudflared?

4.0.5

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Update with a system using the locally managed tunnel

**Comment by elcajon** [comment]
i will check now, should we restore the last version until then?

**Comment by elcajon** [comment]
I assume the problem is this part:

https://github.com/brenner-tobias/addon-cloudflared/blob/efc8da58bb1ccf64adfcc7af7e76efbdd0fa68b9/cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh#L282-L284

may be that the environment variable isn't accessible from the already running script

**Comment by brenner-tobias** [comment]
Thanks everyone for raising and sorry for this bug.
Should be fixed in the just released [4.0.7](https://github.com/brenner-tobias/addon-cloudflared/releases/tag/v4.0.7), so please update and let me know if this is not the case
