### ISSUE TITLE
CLOUDFLARED_LOG: unbound variable on 4.0.6

### ISSUE THREAD

**Issue by joaofidelix** [brenner-tobias/addon-cloudflared#277]
### The problem

After install 4.0.6 i get this error on startup:

`-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.0.6
 You are running the latest version of this add-on.
 System: Ubuntu 20.04.5 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 2022.12.7
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
Log level is set to INFO
[10:25:13] INFO: Checking add-on config...
[10:25:13] INFO: Checking for existing certificate...
[10:25:13] INFO: Existing certificate found
[10:25:13] INFO: Checking for existing tunnel...
[10:25:13] NOTICE: No tunnel file found
[10:25:13] INFO: Creating new tunnel...
/etc/s6-overlay/scripts/cloudflared-config.sh: line 146: CLOUDFLARED_LOG: unbound variable
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.`

### What version of Cloudflared has the issue?

4.0.6

### What was the last working version of Cloudflared?

4.0.5

### What type of installation are you running?

Home Assistant Supervised

### Steps to reproduce the issue

Update to last version

**Comment by olibos** [comment]
I have the same issue

**Comment by Gamerayers** [comment]
Same

**Comment by OH010** [comment]
same

**Comment by tarheelz** [comment]
Y'all beat me to it.

**Comment by bighippo999** [comment]
and me. I've been trying to figure out how to rollback to see if that worked. Guess I'll wait to go forward :)

**Comment by hknorst** [comment]
Same here

**Comment by elcajon** [comment]
Anybody able to test if #278 fixes the problem?

**Comment by lbouriez** [comment]
Same

**Comment by 3djc** [comment]
Same issue here as well

**Comment by ilsalgo** [comment]
Same for me :(

**Comment by srk23** [comment]
Same for me.  Just rolling back to the previous version...

**Comment by brenner-tobias** [comment]
@joaofidelix pls close if this works fine for you

**Comment by oNSXo** [comment]
4.0.7 does solve it for me.

**Comment by joaofidelix** [comment]
Perfect. 4.0.7 works fine!
