### ISSUE TITLE
New version of cloudflared

### ISSUE THREAD

**Issue by iosoft** [brenner-tobias/addon-cloudflared#28]
Hello,

Your cloudflared addon is just awesome, very important and priceless and money saver for me.

I just noticed that there is a new version of cloudflared library.
https://github.com/cloudflare/cloudflared/blob/master/RELEASE_NOTES

Lookin forward to get a addon update also.

Thanks for your great work.
Regards

**Comment by brenner-tobias** [comment]
I just updated to the new version yesterday. I am still working on automating the deployment process, but I will release the update soon.

**Comment by iosoft** [comment]
> I just updated to the new version yesterday. I am still working on automating the deployment process, but I will release the update soon.

Keep up the GREAT WORK!

**Comment by iosoft** [comment]
Just got the update.
Thanks a lot.
