### ISSUE TITLE
Image ghcr.io/brenner-tobias/cloudflared/aarch64:4.0.7 does not exist for addon_9074a9fa_cloudflared

### ISSUE THREAD

**Issue by diogopms** [brenner-tobias/addon-cloudflared#280]
### The problem

I've updated today my cloudflare addon, and I'm getting this error (Pi3+ using HassOS)

![image](https://user-images.githubusercontent.com/2445019/208967200-5bf47d84-ab0e-46eb-89b9-ca0a3d546c32.png)

### What version of Cloudflared has the issue?

4.0.7

### What was the last working version of Cloudflared?

4.0.6

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

![image](https://user-images.githubusercontent.com/2445019/208967986-58d3f327-c159-450a-8cd9-9f95e060be0f.png)

### Steps to reproduce the issue

- Updated the addon to 4.0.6
- Hardware Pi3+

**Comment by elcajon** [comment]
Please have a look at the discussion [here](https://github.com/brenner-tobias/addon-cloudflared/pull/278#issuecomment-1361520063), addressing the same problem. Let me know if this is not working for you.

**Comment by diogopms** [comment]
@elcajon , thanks 🙏🏻 
This solved the issue for pi3+
