### ISSUE TITLE
Problem with connection with Cloudflared 4.0.8 (and latest HA version)

### ISSUE THREAD

**Issue by cortado** [brenner-tobias/addon-cloudflared#303]
### The problem

I get a lot of these after updating Cloudflared and HA to latest version. Never had ANY connection issues before – it just worked like it was not there. I get these problems both in browser and in iPhone app. It is worst with the things that take some time to load, like Node Red dashboard - that I can hardly access anymore because it just stops loading when non on local wifi. 

### What version of Cloudflared has the issue?

4.0.8

### What was the last working version of Cloudflared?

4.0.7

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
A lot of these:

2023-01-19T15:26:53Z ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp 172.30.32.1:8123: connect: connection refused" connIndex=0 dest=https://xxx.xxx.xxx/api/websocket ip=xxx.xxx.xxx.xxx type=ws
2023-01-19T17:06:28Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp: lookup homeassistant on 127.0.0.11:53: read udp 127.0.0.1:35133->127.0.0.11:53: i/o timeout" cfRay=78c128a64c030b55-OSL ingressRule=0 originService=http://homeassistant:8123
```

### Steps to reproduce the issue

Cannot really say

### Additional information

Running on RPi3, everything else is normal, but Cloudflared is acting up.

**Comment by brenner-tobias** [comment]
This feels like a Cloudflare hiccup, so I suggest to wait for a couple of days and check again. Maybe re-start the add-on if this has not happened already.

If it persists, you have to create an [issue in the Cloudflare repository](https://github.com/cloudflare/cloudflared/issues), it might be an issue with Cloudflare 2023.1.0, which we released with v4.0.8., though I do not see any issues being raised there that suggest that this might be the case.

**Comment by WvanWaas** [comment]
Same stuff but lost the error by now due to an re-install of the Cloudflared 
Current log says it's working fine but the actual page gives me a reloading button that must be cache as another browser stays empty: 
`2023-01-20T21:39:23Z INF Connection 4dbca952-fcad-4cc7-986d-c50cfdfb8826 registered with protocol: quic connIndex=0 ip=198.41.200.73 location=VIE
2023-01-20T21:39:23Z INF Connection 613de636-63bf-4016-a51d-88bb1eceec18 registered with protocol: quic connIndex=1 ip=198.41.192.107 location=AMS
2023-01-20T21:39:24Z INF Connection bc460034-b509-43e9-be5f-e600f69a9d5e registered with protocol: quic connIndex=2 ip=198.41.192.47 location=AMS
2023-01-20T21:39:26Z INF Connection 212eccb3-6f44-432a-85a3-061a67231482 registered with protocol: quic connIndex=3 ip=198.41.200.33 location=VIE` 

Everything looks healthy but it's not working.

**Comment by brenner-tobias** [comment]
Are you using domains from Freenom?

**Comment by cortado** [comment]
No, .com hosted by Cloudflare.

**Comment by cortado** [comment]
Still had the problems yesterday, with timeout when trying to use Node Red via cell network. Have done couple of restarts and now update of HA. Will se if things are better today.

**Comment by WvanWaas** [comment]
@brenner-tobias yes my domain is from Freenom. I have some owned domains but didn't want to use it for my home yet.

**Comment by atus** [comment]
I have had the same issue for some months. Of three installs, only one is misbehaving. Two of them share the same geography and mostly target the same cloudflare servers where one them isn't working.

From logs.
`2023-01-23T21:53:05Z ERR Failed to refresh protocol error="lookup protocol-v2.argotunnel.com on 127.0.0.11:53: server misbehaving"

2023-01-23T21:53:05Z ERR Connection terminated error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 `

It's also interesting to mention that if i try to ssh into the rpi, by using wireguard and ssh addons on it, i will maybe get in and when I do, I will find a nearly unresponsive rpi and completely unreachable HA.

Looking at cloudflare tunnel status, my other tunnels are up for weeks and this one is trying to scrape together a day. I've switched out the rpi, sd card, power supply and did a full reinstall with restore. Also removed most addons to try to eliminate other factors but still seeing same issues.

**Comment by kpaaro** [comment]
> I have had the same issue for some months. Of three installs, only one is misbehaving. Two of them share the same geography and mostly target the same cloudflare servers where one them isn't working.
> 
> From logs.
> 
> ```
> 2023-01-23T21:53:05Z ERR Failed to refresh protocol error="lookup protocol-v2.argotunnel.com on 127.0.0.11:53: server misbehaving"
> 
> 2023-01-23T21:53:05Z ERR Connection terminated error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 
> ```
> 
> It's also interesting to mention that if i try to ssh into the rpi, by using wireguard and ssh addons on it, i will maybe get in and when I do, I will find a nearly unresponsive rpi and completely unreachable HA.
> 
> Looking at cloudflare tunnel status, my other tunnels are up for weeks and this one is trying to scrape together a day. I've switched out the rpi, sd card, power supply and did a full reinstall with restore. Also removed most addons to try to eliminate other factors but still seeing same issues.

I have a the same issue with my HA VM, the same errors, with followed by an unresponsive HA.

**Comment by cortado** [comment]
Works now for me. So either the latest HA update, or stuff on Cloudflare side finally make it work again.

**Comment by atus** [comment]
What's the meaning of closing an issue if three other people reported the same symptoms but it works for you? 

Let's leave it up to the maintainer to make a call on closing an issue where multiple people report the same symptoms.

**Comment by cortado** [comment]
Sorry, thought it was the right thing to do. Will repoen :)

**Comment by kpaaro** [comment]
> Works now for me. So either the latest HA update, or stuff on Cloudflare side finally make it work again.

Its not constant, it just happens at some point

**Comment by brenner-tobias** [comment]
@kpaaro are you using a domain from freenom?

**Comment by kpaaro** [comment]
That is correct, is there a issue with those?

**Comment by brenner-tobias** [comment]
Yes unfortunately there are many users with issues (including me) on Freenom domains. It looks like they are having problems or closing their free service without notice. So the only suggestion I can give you now is to get a "proper" domain name from GoDaddy, Namecheap or any other service from your country. 
Please open a new ticket if the problem still ocures with another registrar.

**Comment by kpaaro** [comment]
@brenner-tobias okay thanks for the info, if there is no notice how do we know they are closing their service?

**Comment by atus** [comment]
I'm using not using a freenom domain.

**Comment by brenner-tobias** [comment]
Unfortunately, I do not know to be honest. Their communication strategy is very bad and I am also only aware of this because I tried to get a new domain recently for testing purposes which did not work. So there is not really much we can do there, sorry.

**Comment by brenner-tobias** [comment]
@atus can you please create a new issue for that, so we can have a detailed look into your set-ups and specifics of the problem

**Comment by Electronlibre2012** [comment]
> @kpaaro are you using a domain from freenom?

Hello,

yesterday i lost my google assistant integration, i mean i cant sync anymore and wommand my devices by voice with all my 5 google home.

I find some info about add an icon and fill some more info in setting on Google Action Console, but that did not work.

Today i try again in the middle of the day and it works again.

I have a domain name from freenom...and i use cloudflare addon...sure its related to freenom
