### ISSUE TITLE
Connector outdated

### ISSUE THREAD

**Issue by Webbeh** [brenner-tobias/addon-cloudflared#315]
### The problem

Good morning.

The Cloudflared connector service you are using is currently outdated and will soon need to be updated.

![image](https://user-images.githubusercontent.com/1530837/216924195-ab1ee1c3-6c36-4a09-a492-0abf40268ff2.png)

Thank you very much !

### What version of Cloudflared has the issue?

4.0.9

### What was the last working version of Cloudflared?

4.0.9

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Log in to your Cloudflare dashboard, check your named tunnels.

**Comment by elcajon** [comment]
I have just published a new release (4.0.10) which includes the latest version of the tunnel.
