### ISSUE TITLE
Breaking Upgrade?

### ISSUE THREAD

**Issue by grantyoyo** [brenner-tobias/addon-cloudflared#317]
### The problem

The latest update failed to install on my Home Assistant.

So I thought to uninstall and reinstall, and now the install won't run.

`Failed to install add-on
Can't install ghcr.io/brenner-tobias/cloudflared/aarch64:4.0.10: 404 Client Error for http+docker://localhost/v1.41/images/ghcr.io/brenner-tobias/cloudflared/aarch64:4.0.10/json: Not Found ("no such image: ghcr.io/brenner-tobias/cloudflared/aarch64:4.0.10: No such image: ghcr.io/brenner-tobias/cloudflared/aarch64:4.0.10")`

### What version of Cloudflared has the issue?

4.0.10

### What was the last working version of Cloudflared?

4.0.9

### What type of installation are you running?

Home Assistant Supervised

### Steps to reproduce the issue

1) Install Cloudflared from Settings > Add-ons

**Comment by grantyoyo** [comment]
`grantduke@Grants-MacBook-Pro cloudflared % docker save -o image1.tar ghcr.io/brenner-tobias/cloudflared/aarch64:4.0.9
grantduke@Grants-MacBook-Pro cloudflared % ls
image1.tar
grantduke@Grants-MacBook-Pro cloudflared % docker save -o image2.tar ghcr.io/brenner-tobias/cloudflared/aarch64:4.0.10
Error response from daemon: reference does not exist
grantduke@Grants-MacBook-Pro cloudflared % 
`

Here's more evidence of a reference that doesn't seem to exist for the latest release

**Comment by brenner-tobias** [comment]
works fine for all my test instances. Maybe something was not populated properly? Can you try again?

**Comment by grantyoyo** [comment]
Hi there, still the same error comes back. And this is even on a different ISP connection.

grantduke@Grants-MBP ~ % docker save -o image2.tar ghcr.io/brenner-tobias/cloudflared/aarch64:4.0.10
Error response from daemon: reference does not exist
grantduke@Grants-MBP ~ % 

But 4.0.9 still works
grantduke@Grants-MBP ~ % docker save -o image2.tar ghcr.io/brenner-tobias/cloudflared/aarch64:4.0.9
grantduke@Grants-MBP ~ % ls
Applications		Music			VirtualBox VMs
Desktop			
Documents		Pictures
Downloads		Postman			image2.tar
Library			Public			test.json
Movies			PycharmProjects		test.py
grantduke@Grants-MBP ~ %

**Comment by grantyoyo** [comment]
With help of one of my colleagues, he pointed out that I can't save directly save the image to a tar file. I first need to docker pull and then docker save.

I will be updating my device later this evening after uploading the loading the tar file

**Comment by grantyoyo** [comment]
@brenner-tobias I was able to resolve the issue. The problem was not on your side but on my side with the MTU issue on my PPPoE dial-out to WWW. Fibre Operator changed backhaul links, and thus required a lower MTU value
