### ISSUE TITLE
Every couple weeks I get Error 1003

### ISSUE THREAD

**Issue by Fuzionist1** [brenner-tobias/addon-cloudflared#327]
### The problem

Cloudflared works great then every couple weeks gets this error and I have to log into Cloudflare, delete the DNS CName entry, and restart Cloudflared add-on.
  

![Screenshot 2023-02-20 145539](https://user-images.githubusercontent.com/13238025/220189028-d807c3c4-912e-4d93-bb3c-7fc946ba0d91.png)
![Screenshot 2023-02-20 145512](https://user-images.githubusercontent.com/13238025/220189033-aaa68bb0-f4fd-48f9-a7c6-03dca856672c.png)

### What version of Cloudflared has the issue?

4.0.10

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
additional_hosts: []
external_hostname: <Redacted> // it is just my personal domain name
```

### Steps to reproduce the issue

Everything works perfectly, then every week or couple weeks, it gets the error shown in the screenshots above.  It's like the add-on is trying to make a new tunnel when there's already one there that it made before.  I'll note that I do not do anything else with Cloudflare or this domain except use it as documented for the add-on.

**Comment by dejasound** [comment]
I am having the exact same issue on my HomeAssistant.

**Comment by Fuzionist1** [comment]
Thank you for responding!  I have setup the managed tunnel now and I'll report back if the above mentioned issue persists.  Even before it would take a week or more for it to happen again - but it always happened again...
