### ISSUE TITLE
Need to delete cloudflare DNSs everytime before i restart the addon 

### ISSUE THREAD

**Issue by ericgu08** [brenner-tobias/addon-cloudflared#342]
### The problem

I had the same problem problem described in issue #259 tonight.  Long story short, after installing and configuring the add-on, the tunnel is created successfully.  However at the next restart it fails to create the DNS entry with this message in the log:

[09:38:09] INFO: Creating DNS entry ###.###.tk...
Failed to add route: code: 1003, reason: An A, AAAA, or CNAME record with that host already exists.
[09:38:11] FATAL: Failed to create DNS entry ###.###.tk.

The problem is when the "external_hostname" is written in CAPITALS, you will have the issue, because the CNAME DNS entry in the Cloudflare Portal is stored in lowercase. 

At the next load, when the hostname is compared with existing DNS entries, the comparaison fails because the verification is probably case sensitive, then it tries to recreate the entry and fails because it already exists.

### What version of Cloudflared has the issue?

4.0.12

### What type of installation are you running?

Home Assistant Supervised

### Anything in the logs that might be useful for us?

```txt
[09:38:09] INFO: Creating DNS entry ###.###.tk...
Failed to add route: code: 1003, reason: An A, AAAA, or CNAME record with that host already exists.
[09:38:11] FATAL: Failed to create DNS entry ###.###.tk.
```

### Steps to reproduce the issue

In an existing installation, if the hostname is written in capitals (ex. HOST.domain.com), the add-on will fail to load.

**Comment by a-wolter** [comment]
I can confirm the issue with the existing DNS record. I have 100% rate the addon fails to start after the record was created by the addon in the first run. 
After deleting the record in cloudflare the add-on will start again until it has to start again.

```
[00:12:53] INFO: Creating DNS entry ha...
Failed to add route: code: 1003, reason: An A, AAAA, or CNAME record with that host already exists. For more details, refer to <https://developers.cloudflare.com/dns/manage-dns-records/troubleshooting/records-with-same-name/>.
[00:12:54] FATAL: Failed to create DNS entry ha.
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
```

**Comment by rwese** [comment]
Can't confirm this.

I tried restarting - ok
I tried stopping and starting - ok

Are you using a lower record like `xxx.sub.domain.tld`?

```
 Add-on version: 4.0.12
 System: Home Assistant OS 9.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.3.3
 Home Assistant Supervisor: 2023.03.1
```

**Comment by a-wolter** [comment]
Still have the same issue with 4.0.14

-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.0.14
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.5  (aarch64 / odroid-n2)
 Home Assistant Core: 2023.3.6
 Home Assistant Supervisor: 2023.03.2
-----------------------------------------------------------


`
[23:00:08] INFO: Validating config file...
Validating rules from /tmp/config.json
OK
[23:00:08] INFO: Creating DNS entry ha...
Failed to add route: code: 1003, reason: An A, AAAA, or CNAME record with that host already exists. For more details, refer to <https://developers.cloudflare.com/dns/manage-dns-records/troubleshooting/records-with-same-name/>.
[23:00:09] FATAL: Failed to create DNS entry ha.
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container. `
