### ISSUE TITLE
A new version of cloudflared is available.

### ISSUE THREAD

**Issue by anzenketh** [brenner-tobias/addon-cloudflared#372]
### The problem

When logging into the cloudflared portal in tunnels it states:

A new version of cloudflared is available. Visit our [downloads](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation) page to upgrade.

### What version of Cloudflared has the issue?

4.1.0

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
Looks like a release happens just yesterday:
https://github.com/cloudflare/cloudflared
```

### Steps to reproduce the issue

Login to cloudflare at Websites> domain > Traffic > Cloudflare Tunnel > Launch Zero Trust Dashboard > Access > Tunnels

**Comment by AlecRust** [comment]
https://github.com/brenner-tobias/addon-cloudflared/discussions/371
