### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by ductu3590** [brenner-tobias/addon-cloudflared#397]
### The problem

Failed to install add-on
Can't install ghcr.io/brenner-tobias/cloudflared/aarch64:4.1.5: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=4.1.5&fromImage=ghcr.io%2Fbrenner-tobias%2Fcloudflared%2Faarch64&platform=linux%2Farm64: Internal Server Error ("Head "https://ghcr.io/v2/brenner-tobias/cloudflared/aarch64/manifests/4.1.5": Get "https://ghcr.io/token?scope=repository%3Abrenner-tobias%2Fcloudflared%2Faarch64%3Apull&service=ghcr.io": context deadline exceeded")

### What version of Cloudflared has the issue?

4.1.5

### What was the last working version of Cloudflared?

4.1.5

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

I cannot install or update Cloudflare. Previously I used Cloudflare 4.1.4 However, because it couldn't update, I deleted it and reinstalled it. And now, I cannot install it with the above error. Bed like, there's something wrong from my Hassio to the Github server, ghcr.io.

I tried pinging these 2 servers but it didn't work. Then I tried to find a way and add the following 3 lines to /etc/host via Terminal:
`140.82.121.34 ghcr.io
185.199.108.154 pkg-containers.githubusercontent.com
185.199.108.153 github.com
`
After adding those 3 lines my HA was able to ping the server. However, the installation still encountered an error. I tried to install some other add-ons like: DHCP Server, Git pull. The installation process is normal, no problem occurs.
![Screenshot](https://github.com/brenner-tobias/addon-cloudflared/assets/97110519/b1f1035e-17b5-476a-95ee-85c547d1d37e)

**Comment by brenner-tobias** [comment]
This looks like an issue with Hassio, which is hard to pin-point from a distance. If possible, I suggest you do a full clean installation of Hassio and set-up everything again.

**Comment by felipecrs** [comment]
Or it may also be a temporary issue with GitHub Container Registry. @ductu3590, are you still experiencing it?

What version of HAOS are you using (if you are using HAOS)?

**Comment by ductu3590** [comment]
It seems to be a silly mistake of the SD card. When I remove the SD card, and reinsert it then press update again (hopefully though) but all of a sudden it works. I was able to install and update HAOS versions normally. Thanks for your help!!!
