### ISSUE TITLE
Warning for Nginx Proxy Manager

### ISSUE THREAD

**Issue by jcat59** [brenner-tobias/addon-cloudflared#40]
Within my system logs - I'm getting this message "22-02-07 10:34:39 WARNING (MainThread) [supervisor.addons.options] Option 'nginxproxymanager' does not exist in the schema for Cloudflared"

I'm not currently using nginx proxy manager for anything. Is there an advantage to using it, in addition to the cloudflare tunnel? Currently I'm using the tunnel to access HA, and one additional host. I have a domain through cloudflare.

**Comment by brenner-tobias** [comment]
It looks like you have the option `nginxproxymanager` defined in your config. I suggest to delete it if you are not using nginx. 
It is not useful unless you want to have more sophisticated reverse proxy possibilites.

**Comment by jcat59** [comment]
That did the trick, thanks.
