### ISSUE TITLE
Can one domain in Cloudflare be used to tunnel into several different networks?

### ISSUE THREAD

**Issue by fredfrom** [brenner-tobias/addon-cloudflared#410]
### The problem

I want to connect to HA in my and some other people's houses. Can I use one domain to connect to several instances on different networks by using subdomains? If yes, how would I configure it? Should I use CNAME or A record and what should I enter under the IPv4 address (required) in Cloudflare?

### What version of Cloudflared has the issue?

4.1.7

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Add a subdomain in Cloudflare and try to connect it to another instance of Cloudflare in another HA on another network.

**Comment by antsmartti** [comment]
I do this and it works well. I didn't get it to work when I have two instances of HA running on the same network, but it works otherwise. The process is the same for each instance, just create a new tunnel in [Zero Trust](https://one.dash.cloudflare.com/) for each HA instance and type in a different subdomain for each.

**Comment by brenner-tobias** [comment]
As stated by @antsmartti this is working with two separate subdomains. If you require further support, please open a discussion for that.

**Comment by fredfrom** [comment]
Found my issue. The tunnel name default is homeassistant. In order to open a mies tunnel the existing one has to be renamed by going into cloudflared config, select edit as yaml under the three dot menu and adding tunnel _names: otherNameThatIsntHomeassistant

**Comment by antsmartti** [comment]
I used the manual setup instead and copied the token from Cloudflare and defined the name of the tunnel myself. Seemed a bit easier. But great job either way!
