### ISSUE TITLE
Reconsider making aa docker container for the Cloudflared addon

### ISSUE THREAD

**Issue by mjf55** [brenner-tobias/addon-cloudflared#415]
### The problem

As was opened back in Aug 2022, https://github.com/brenner-tobias/addon-cloudflared/issues/136, the user asked if this addon could be installed with docker-compose.  The response was that only HA OS or HA Supervised installations could install it.

My question / request is to make/ modify this addon so it could be containerize allowing and run as a standalone container allowing those of us running Ha in a container to have this functionality.

What would it take to do it?

### What version of Cloudflared has the issue?

4.1.7

### What type of installation are you running?

Other

### Add-on YAML Configuration

```yaml
Home Assistant running as a docker container along side of other containers ( node-red, esphome, etc)
```

### Steps to reproduce the issue

n/a

**Comment by brenner-tobias** [comment]
Thanks for raising this. The reason, why we are not going to implement this is very simple: There is already a [Docker Container from Cloudflared](https://hub.docker.com/r/cloudflare/cloudflared), that you can very easily deploy and run.
Simply log into your Cloudflare Zero Trust Dashboard, create a tunnel and follow the steps for a Docker deployment (see [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/remote/)). There are also multiple tutorials online that describe this process, e.g. [this one](https://thedxt.ca/2022/10/cloudflare-tunnel-with-docker/).

**Comment by mjf55** [comment]
Thank you.  I did not know that.

**Comment by dsolva** [comment]
I got started with this cloudflared add on in home assistant. Now that I moved to docker and following the tutorial above I sadly learned that docker cloudflared doesn't create dns entries depending on changes in the config.yml which this addon does. Its a pain to go to cloudflare to mantain that.

I havent tested it but someone tried to solve it here https://blog.scubbo.org/posts/cloudflare-tunnel-dns/

**Comment by brenner-tobias** [comment]
I have to disagree. The way to work with a tunnel is to create it in a remote managed way (e.g. following [this tutorial)](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/remote/). This way, the only place you have to configure the hosts you want to work with is in Cloudflare Zero Trust Dashboard.
