### ISSUE TITLE
Change of location for config and certificate files

### ISSUE THREAD

**Issue by elcajon** [brenner-tobias/addon-cloudflared#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I recently thought about changing the location for cert.pem and tunnel.json from /data to /{ssl or share}/cloudflared. 
This would benefit in making both files reusable on other hosts for redundancy.

I also thought about providing the possibility to add config.yml (.yml, not .json) manually. Which, if file exists, leads to starting clouflared tunnel with the manually created config file. This would benefit allow making more complex service configuration with other ingress config options. 

In my opinion this could be realized with another optional configuration option (e.g. "data_path").

**Describe alternatives you've considered**

**Additional context**

In addition I would suggest (independent of "data_path") moving the automatically created config.json file outside the persistent /data storage as it is regenerated on every restart either way. 

@brenner-tobias  I could take a look at it tonight if you think the changes make sense as well.

**Comment by brenner-tobias** [comment]
Makes sense, great suggestion. Feel free to have a go at it, happy to also look into it over the weekend.

**Comment by elcajon** [comment]
#44  will add base functions and should work without interfering already existing configurations

I will add the proposed custom config.yml functionality in a separate PR.
