### ISSUE TITLE
How to make a tunnel to a url?

### ISSUE THREAD

**Issue by gajotnt** [brenner-tobias/addon-cloudflared#436]
### The problem

Maybe a very stupid question, making a tunnel to a network device is easy, but how can i make a tunnel to a ip adress with a path

for example i have a tunnel that gives me acess to Home Assistant

```
- hostname: ha.domain.com
  service: https://192.168.1.1:8443
```

but would like guests to have acess to a dashboard

`https://192.168.1.177:8443/lovelace-guest`

the easy logic would be:
```
- hostname: guest.domain.com
  service: https://192.168.1.1:8443/lovelace-guest
```

but it doesnt work, maybe its not even possible?

### What version of Cloudflared has the issue?

4.1.9

### What was the last working version of Cloudflared?

4.1.9

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

the easy logic would be:
```
- hostname: guest.domain.com
  service: https://192.168.1.1:8443/lovelace-guest
```

**Comment by brenner-tobias** [comment]
Unfortunately, this it not (yet) possible with Cloudflared, see [this issued](https://github.com/cloudflare/cloudflared/issues/563) I raised early last year.
As far as I am aware, you have to use some sort of proxy (e.g. the [Nginx Proxy Manager HA add-on](https://github.com/hassio-addons/addon-nginx-proxy-manager)) and configure the path and the other forward of the plain URL there after forwarding the full subdomain to it.
So unfortunately there is nothing that we can do about this in the add-on, but feel free to post into my issue to give it some traction.

**Comment by gajotnt** [comment]
thanks for the input, that sheds some light to a possible solution :)
