### ISSUE TITLE
Raspberry PI 3 issue

### ISSUE THREAD

**Issue by kimasplund** [brenner-tobias/addon-cloudflared#449]
### The problem

So im experiencing some issues on rpi3. i have several rpi4's running without any issues using the tunnel token. and it works flawlessly. But the rpi3 absolutley refuse to cooperate. it opens the tunnel just fine but then when i try to open it in a browser it just gives "400: Bad Request". All the settings on the ha's are identical on both rpi3 and rpi4 (well except the tunnel key that is)

### What version of Cloudflared has the issue?

4.2.1

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

install it on rpi3?

**Comment by elcajon** [comment]
I am sorry but, without more information (add-on and http config, tunnel config, logs...) nobody here will be able to help.
