### ISSUE TITLE
Debug log level is not working as expected

### ISSUE THREAD

**Issue by Solom00n** [brenner-tobias/addon-cloudflared#456]
### The problem

The mapping between Home Assistant and Cloudflared log levels, as currently defined in the [cloudflared-config.sh](https://github.com/brenner-tobias/addon-cloudflared/blob/0519e0e96fb4ee3e11935fdbbe014da1fba6d16b/cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh#L315-L328) script, seems incorrect to me. The current mapping prevents the use of Cloudflared **debug** level, which can be used to log and display the request URL, method, protocol, content length, as well as all request and response headers (see [doc : tunnel logs](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/monitor-tunnels/logs/#view-logs-on-the-server)). I think this is just a typo, and the fix is as simple as changing the mapping for trace and debug levels as follows:
```
# Map Home Assistant log levels to Cloudflared
if bashio::config.exists 'log_level' ; then
    case $(bashio::config 'log_level') in
        "trace") log="debug";;
        "debug") log="debug";;
        "info") log="info";;
        "notice") log="info";;
        "warning") log="warn";;
        "error") log="error";;
        "fatal") log="fatal";;
    esac
else
    log="info"
fi
```

### What version of Cloudflared has the issue?

4.2.2

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: xxxxxx
additional_hosts: []
log_level: debug
```

### Anything in the logs that might be useful for us?

```txt
-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.2.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.4  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2023.8.1
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
Log level is set to DEBUG
[12:15:40] DEBUG: Cloudflared log level set to "info"
...
```

### Steps to reproduce the issue

1. set the log level to DEBUG in the configuraton tab

**Comment by elcajon** [comment]
We had a [discussion](https://github.com/brenner-tobias/addon-cloudflared/pull/48#issuecomment-1039379363) about this some time ago. We had put the focus on analyzing errors from an add-on perspective, not necessarily on verbose output from Cloudflared.

For the "debug" log output, I'd like to leave that at the current logic (to be able to further analyze add-on specific problems in a reasonable way). But maybe we could switch on the Cloudflared debug mode for "trace" severity.

**Comment by Solom00n** [comment]
Sorry I didn't find that thread. Now I see the logic behind this. Anyway, if I may say so, I think it's more correct to have another option to control the Cloudflared logs, so we can have the best of both worlds. For example, in my use case, I'm only interested in the addon's error logs, but I need the Cloudflared debug logs to check the traffic going through the tunnel, which is an important feature in my opinion. You could set this additional option to fatal as default, and even hide it in the configuration tab, so that everything is left as it is now. Otherwise, if you think it's not worth it, we can give the trace/debug mapping a shot, but I feel it's a bit of a stretch.

**Comment by elcajon** [comment]
My time is a little bit tight at the moment, but if you would like to, feel free to create a PR for the solution that you prefer.

**Comment by Solom00n** [comment]
Sadly I am short on time too and also managed to use Cloudflare logs for debugging purposes so my interest in this issue has faded at this time. Feel free to close it if it's not worth your time. Anyway thanks for your work.
