### ISSUE TITLE
The URL provided by the plugin results in a 404 error on a Cloudflare page.

### ISSUE THREAD

**Issue by smarqu3s** [brenner-tobias/addon-cloudflared#458]
### The problem

The URL provided by the plugin after initial configuration results in a 404 error on a Cloudflare page:
<img width="816" alt="image" src="https://github.com/brenner-tobias/addon-cloudflared/assets/35402652/6f84479c-da9d-4061-865d-4ddd1c4ed692">

<img width="926" alt="image" src="https://github.com/brenner-tobias/addon-cloudflared/assets/35402652/70d3ab15-46f5-4998-b028-23d37af4d2fa">

There are other people facing the same issue [here](https://community.home-assistant.io/t/new-add-on-cloudflared/361637/586?u=smarqu3s). 

Please let me know if any further information is needed. 

Thank you!

### What version of Cloudflared has the issue?

4.2.2

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

- Install the plugin
- Set the Additional Hosts and Cloudflare Tunnel Name
- Start the plugin
- Follow the steps and navigate the provided URL in the logs

**Comment by elcajon** [comment]
I'm afraid there's nothing we can do from an add-on perspective, as the URL is not created by us but by cloudflared.
There is already an ongoing discussion here https://community.cloudflare.com/t/argo-tunnel-login-all-attempts-to-login-return-404-impossible-to-create-any-tunnels/542225/16

**Comment by smarqu3s** [comment]
> I'm afraid there's nothing we can do from an add-on perspective, as the URL is not created by us but by cloudflared. There is already an ongoing discussion here https://community.cloudflare.com/t/argo-tunnel-login-all-attempts-to-login-return-404-impossible-to-create-any-tunnels/542225/16

Understood. I didn't know that the URLs were generated by Cloudflare. 

It looks like they have already resolved the issue and the URLs should be functional again. 
I'll give it a shot later today. 

Appreciate your help!
