### ISSUE TITLE
After restore backup Bad Gateway

### ISSUE THREAD

**Issue by antoweb** [brenner-tobias/addon-cloudflared#467]
### The problem

Hello, i have restored a full backup of Home Assistant to HA. Cloudflared addon is correctly configured with same api key as before restore. (the same of old server).

All works good from internal lan but form cloudflare dns hostname i obtain 502 Bad Gateway.

In cloudflared logs i see

responding to traffic from cloudflared: dial tcp 192.168.1.10:8123: connect: no route to host" connIndex=2 

Effectively the new server has another private ip, 192.168.1.9. Changing private ip of  HA the tunnel works good, So the question is:
How to restore the tunnel if i change the HA private ip?

### What version of Cloudflared has the issue?

4.2.5

### What was the last working version of Cloudflared?

4.2.5

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

- Create a new server home assistant os
- Use another private ip address
-  Restore Backup of the old server

**Comment by brenner-tobias** [comment]
Thanks for raising this. 
In the tunnel configuration, we are using the hostmane of your system to forward the requests:

[`config=$(bashio::jq "${config}" ".\"ingress\" += [{\"hostname\": \"${external_hostname}\", \"service\": \"${ha_service_protocol}://homeassistant:$(bashio::core.port)\"}]")`](https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh)

So this should work if the IP changes, but seeing that it does not, I suspect that the hostname does not update with the new IP and therefore still resolve to the old one.

Can you open "http://homeassistant:8123" (or whatever Port you are using) in your browser, if the new IP is used?

@elcajon do you have an idea, why this is not resolving properly? We could think about changing `"${ha_service_protocol}://homeassistant:$(bashio::core.port)\"` to something like 
`"${ha_service_protocol}://$(bashio::supervisor.ip_address):$(bashio::core.port)\"` but I am not sure this is better...

Maybe we could also call `bashio::dns.reset()`, not sure though if this helps...

**Comment by elcajon** [comment]
The two log lines seem a bit strange to me. We call the (internal) hostname `homeassistant` via the Docker network, which should be present for every (correct) Home Assistant installation. A name resolution does not take place at this point (if then to the Docker network IP range 172.30.33.0/23).

Probably a complete (debug) log and the general add-on configuration would be helpful. It is also not obvious to me if the tunnel was configured locally or remotely.
