### ISSUE TITLE
Home assistant addon doesn't work

### ISSUE THREAD

**Issue by jafermjj** [brenner-tobias/addon-cloudflared#476]
### The problem

I tried to add the add-on repository in Home assistant, 2023.9.0 and it says the repository is not valid

### What version of Cloudflared has the issue?

latest

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

open home assistant, go to add-on, add via repository, paste: https://github.com/brenner-tobias/addon-cloudflared

**Comment by elcajon** [comment]
Please read the documentation and follow the installation instructions.
