### ISSUE TITLE
Argo tunnel write code 1001

### ISSUE THREAD

**Issue by StijnCleners** [brenner-tobias/addon-cloudflared#489]
### The problem

i don't have argo tunnel on my cloudflare. can it be done in another way?

### What version of Cloudflared has the issue?

4.2.7

### What was the last working version of Cloudflared?

4.2.7

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

when i copy the address from the log file to activate it gives me an error Argo tunnel write code 1001 when i try to activate

**Comment by brenner-tobias** [comment]
This feels like a temporary issue with Cloudflare. Can you re-check?

If this keeps not working for you, I suggest to create a [remote tunnel](https://github.com/brenner-tobias/addon-cloudflared/wiki/How-tos#how-to-configure-remote-tunnels) following these instructions.

Please re-open if you have any follow-up questions.

**Comment by StijnCleners** [comment]
No still does not work. Check screenshot
I don't have the agro tunnel on cloudflare. It costs 5€ per month to use
Argo.


Op zo 1 okt. 2023 20:17 schreef Tobias Brenner ***@***.***>:

**Comment by brenner-tobias** [comment]
There is a free version on Cloudflare, so no need to use anything else

**Comment by StijnCleners** [comment]
Ivm using the free version but it's not working 😀.
Can you try if it works for you?

Op do 5 okt. 2023 08:53 schreef Tobias Brenner ***@***.***>:

**Comment by brenner-tobias** [comment]
You can definitely use the free version of Cloudflare with Cloudflare Zero Trust and create a managed tunnel there. Not sure what the "it is not working" is referring to, what are you trying to do / which part is not working?

**Comment by StijnCleners** [comment]
The part where you go to cloudflare with the link provided in home
assistant. If is try to authorize i get the Argo tunnel error

Op vr 6 okt. 2023 00:30 schreef Tobias Brenner ***@***.***>:

**Comment by brenner-tobias** [comment]
As mentioned, I suggest to create a Remote Managed Tunnel following [this documentation](https://github.com/brenner-tobias/addon-cloudflared/wiki/How-tos#how-to-configure-remote-tunnels). For that, you have to login to Cloudflare Zero Trust (there is a free option at the very bottom when selecting your plan) and create the tunnel there before entering the token in our Cloudflare Add-On
