### ISSUE TITLE
Troubleshooting Webhook failed error 503

### ISSUE THREAD

**Issue by Lux315** [brenner-tobias/addon-cloudflared#493]
### The problem

The troubleshooting for the webhook error 503 is described here, but its outdated:
https://github.com/brenner-tobias/addon-cloudflared/wiki/Troubleshooting#webhook-failed-with-the-status-code-503-while-updating-location

The article says the workaround is to create a firewall rule, but cloudflare changed this feature, as described here:
https://developers.cloudflare.com/waf/reference/migration-guides/firewall-rules-to-custom-rules/#new-skip-action-replacing-both-allow-and-bypass-actions

the „allow“ got replaced by skip. I cant figure out, what i have to select what should be skipped.

This options are available:

All remaining custom rules

All rate limiting rules

All managed rules

All Super Bot Fight Mode Rules
More components to skip

Zone Lockdown

User Agent Blocking

Browser Integrity Check

Hotlink Protection

Security Level

Rate limiting rules (previous version)

Managed rules (previous version)

Happy for any help! Thanks in advance

### What version of Cloudflared has the issue?

4.2.7

### What was the last working version of Cloudflared?

unknown

### What type of installation are you running?

Home Assistant Supervised

### Steps to reproduce the issue

- create cloudflare tunnel
- try to send location updates via remote to ha

**Comment by brenner-tobias** [comment]
Thanks for raising this. If I understand your linked article correctly, you should check "All remaining custom rules" under "WAF components to skip: "

Can you please check, if this solves the issue for you? If this is the case, I will update the Wiki entry as well.

**Comment by DerRuedi0** [comment]
> Thanks for raising this. If I understand your linked article correctly, you should check "All remaining custom rules" under "WAF components to skip: "
> 
> Can you please check, if this solves the issue for you? If this is the case, I will update the Wiki entry as well.

If you activate "All remaining custom rules", it works again. I had exactly the same problem just now. It is very important that you delete the HA server in the HA Companion App once and add it completely new afterwards, otherwise the 503 error persists.

**Comment by Lux315** [comment]
Im not exactly sure what fixed it for me. I randomly activated all rules at first to be skipped. Nothing changed.

So ive paused the rule after maybe a hour of testing with an Android phone.

IOS still didnt work, so ive reset the IOS App and added my server again and now its just working fine without any rule?

Theres no rule in my Cloudflare now and works perfectly. Maybe it learns that these calls are fine?

**Comment by DerRuedi0** [comment]
> Theres no rule in my Cloudflare now and works perfectly. Maybe it learns that these calls are fine?

I suspect that if too many post requests are sent to Cloudflare, sooner or later the 503 error will appear again without the "Skip all remaining custom rules".

**Comment by brenner-tobias** [comment]
Thanks for your feedback. I updated the[ Wiki Article](https://github.com/brenner-tobias/addon-cloudflared/wiki/Troubleshooting) accordingly
