### ISSUE TITLE
Umlauts in the domain

### ISSUE THREAD

**Issue by DerRuedi0** [brenner-tobias/addon-cloudflared#496]
### The problem

Hello,

I would like to use my existing domain for the addon, but unfortunately it is not possible because my domain contains umlauts.

The problem is quite easy to identify, the regex (validHostnameRegex) in cloudflared-config.sh prevents the use of umlauts, can this possibly be adjusted?

Best regards

### What version of Cloudflared has the issue?

4.2.7

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Specifies a domain with umlauts (ü, ö, ä) in the configuration for External hostnames.

**Comment by brenner-tobias** [comment]
Thanks for raising this, definitely something we missed and should fix.

I will look into it as soon as possible. If you have a suggestion for the updated regex string it might save me some time ;-)

**Comment by DerRuedi0** [comment]
> Thanks for raising this, definitely something we missed and should fix.
> 
> I will look into it as soon as possible. If you have a suggestion for the updated regex string it might save me some time ;-)

I don't have too much experience with regex but this one should do it.

`^((([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])|([äöüÄÖÜß]|[äöüÄÖÜß][a-zA-Z0-9\-]*[äöüÄÖÜß]))+\.)*([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])$`

Thanks for the fix.

**Comment by brenner-tobias** [comment]
Thanks, I ended up taking another route, see my PR #499

**Comment by brenner-tobias** [comment]
@DerRuedi0 I just merged the fix into our Edge Repository. If you want to use it directly, feel free to use [this repo](https://github.com/brenner-tobias/ha-addons-edge) for install it right now. Please be aware that the edge repo has a slightly higher chance of being unstable or introducing bugs that will not end up in the stable repo.
I assume I will release the current edge version in a couple of days to the stable version, so if you can wait, it will be available there as well.
