### ISSUE TITLE
Cloudflared HA Add-On wont Start

### ISSUE THREAD

**Issue by NigelBrownless** [brenner-tobias/addon-cloudflared#497]
### The problem

When clicking on the Start button the Add-On does not Start. 
I looked int he Logs and have this:
23-10-10 14:37:38 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Cloudflared to start, took more then 120 seconds
I used the Terminal to run the ha addons start command and the following errors was presented:
Post "http://supervisor/addons/9074a9fa_cloudflared/start": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### What version of Cloudflared has the issue?

4.2.7

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: remotehomelab.co.uk
additional_hosts: []
log_level: trace
```

### Anything in the logs that might be useful for us?

```txt
23-10-10 14:37:38 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Cloudflared to start, took more then 120 seconds
I used the Terminal to run the ha addons start command and the following errors was presented:
Post "http://supervisor/addons/9074a9fa_cloudflared/start": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Steps to reproduce the issue

Just hit the Start button on the Add-On

**Comment by brenner-tobias** [comment]
Can you let me know how you are running HA?

**Comment by NigelBrownless** [comment]
Im running HA OS using ProxMox in a VM.

**Comment by brenner-tobias** [comment]
This seems to be an issue with your HA installation, not sure how we can help here to be honest.

**Comment by NigelBrownless** [comment]
Further Analysis shows that the HA Addon is indeed started. The remote tunnel works. It's as if the GUI doesn't refresh to show Stop/Restart but due to a timeout remains with the Start button showing?

**Comment by NigelBrownless** [comment]
If I add an Additional Host, the DNS entry gets updated on the DNS within CloudFlare successfully too.

**Comment by NigelBrownless** [comment]
So I just updated to HA OS 11.0 from 10.5 and the GUI is now showing correctly. Still using CloudFlared 4.2.7.
