### ISSUE TITLE
[FEATURE] Expose other ports

### ISSUE THREAD

**Issue by Dreaming-Codes** [brenner-tobias/addon-cloudflared#5]
**Is your feature request related to a problem? Please describe.**
Expose MQTT ports.

**Describe the solution you'd like**
Possibility to create also other tunnels for other ports.

**Comment by Dreaming-Codes** [comment]
I realized that it can be done with
nginxproxymanager

**Comment by brenner-tobias** [comment]
I just recently release v0.2.x with exactly that feature. You can now configure additional hosts with individual ports.
