### ISSUE TITLE
Addon wont start  "is not a valid hostname"

### ISSUE THREAD

**Issue by Jibbonator** [brenner-tobias/addon-cloudflared#500]
### The problem

addon wont start since update to 4.2.8

### What version of Cloudflared has the issue?

4.2.8

### What was the last working version of Cloudflared?

4.2.7

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```
external_hostname: xxxxx.xxxxx.trade
additional_hosts: []
```
### Anything in the logs that might be useful for us?

```txt
[18:57:16] INFO: Checking add-on config...
[18:57:17] FATAL: 'xxxxx.xxxxx.trade' is not a valid hostname. Please make sure not to include the protocol (e.g. 'https://') nor the port (e.g. ':8123') and only use lowercase characters in the 'external_hostname'.
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

### Steps to reproduce the issue

Start the addon

**Comment by MarcoGos** [comment]
I have simular problems with my hostname. Restored cloudflare 4.2.7 and everything is working again.

**Comment by DerLoco** [comment]
same issue here

**Comment by MrAnonymous722** [comment]
This seems to be related to this commit (https://github.com/brenner-tobias/addon-cloudflared/pull/499/commits/c9b5c6fbbc7993e5fc1e6127ed95819c28658bd2).

If I take the regex now in use and put it into regex101.com and change the regex language to Python, it no longer accepts normal domain names. If this is still an issue in a few hours once I'm off work I can take a look and maybe offer an alternative regex.

**Comment by DerLoco** [comment]
> I have simular problems with my hostname. Restored cloudflare 4.2.7 and everything is working again.

How do I have to do this?

**Comment by Jibbonator** [comment]
I´ve restored from a Backup

> > I have simular problems with my hostname. Restored cloudflare 4.2.7 and everything is working again.
> 
> How do I have to do this?

**Comment by DerLoco** [comment]
Shouldn´t this be possible via SSH? If yes, I appreciate the code line for it

**Comment by MattCheetham** [comment]
Same here.

**Comment by dutch-erik** [comment]
As well:
`[20:08:28] FATAL: 'xxxxxx.net' is not a valid hostname. Please make sure not to include the protocol (e.g. 'https://') nor the port (e.g. ':8123') and only use lowercase characters in the 'external_hostname'.
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.`

**Comment by BrammyS** [comment]
Experiencing the same problem with a `xxx.xxx.dev` hostname.

**Comment by skipishere** [comment]
Unless you're adding additional information you do not need to spam "me too" or +1, just subscribe to the issue to keep an eye for updates

**Comment by Ndrinta** [comment]
Same

**Comment by trevorstuart24** [comment]
experiencing it with .com

**Comment by brenner-tobias** [comment]
Should be fixed in [4.2.9](https://github.com/brenner-tobias/addon-cloudflared/releases/tag/v4.2.9), please check and confirm

**Comment by scoop643** [comment]
> Should be fixed in [4.2.9](https://github.com/brenner-tobias/addon-cloudflared/releases/tag/v4.2.9), please check and confirm

Confirm!

**Comment by brenner-tobias** [comment]
I have to be honest: no idea why this did not work. I checked with multiple domains, plus it was working for me in the Edge release with multiple subdomains, also no issues from other edge users for a day.
Anyways, again sorry, will look into it in detail

**Comment by trevorstuart24** [comment]
> I have to be honest: no idea why this did not work. I checked with multiple domains, plus it was working for me in the Edge release with multiple subdomains, also no issues from other edge users for a day.
> Anyways, again sorry, will look into it in detail

Thank you!
