### ISSUE TITLE
Argo Tunnel error

### ISSUE THREAD

**Issue by Jasom00** [brenner-tobias/addon-cloudflared#503]
### The problem

When updating to version 4.2.8 the tunnel stopped working.
I did not change web address or settings in the add-on.

### What version of Cloudflared has the issue?

4.2.8

### What was the last working version of Cloudflared?

4.2.7

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: xxxxxx.xx
additional_hosts: []
tunnel_name: my-ha
```

### Anything in the logs that might be useful for us?

```txt
[20:15:06] INFO: Checking add-on config...
[20:15:07] FATAL: 'xxxxx.xx' is not a valid hostname. Please make sure not to include the protocol (e.g. 'https://') nor the port (e.g. ':8123') and only use lowercase characters in the 'external_hostname'.
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

### Steps to reproduce the issue

There is no clear way to reproduce the problem, I have tried reinstalling the add-on and it doesn't work either.
The log is always the same:
Is not a valid hostname....

**Comment by lkwr** [comment]
duplicated see #500, #501

**Comment by Jasom00** [comment]
I'm sorry i did not see it. Thank you
