### ISSUE TITLE
Cloudflared is running but sites are not accessable

### ISSUE THREAD

**Issue by MartinKuhl** [brenner-tobias/addon-cloudflared#528]
### The problem

Just a couple of minutes ago, I noticed that my Home Assistant is nor reachable anymore via the public URL. 
Cloudflared is running without issues (what I see in the logs) but not only one Home Assistant instance is affected also 2 other ones. 
Has anyone the same issues?

### What version of Cloudflared has the issue?

4.2.10

### What was the last working version of Cloudflared?

4.2.10

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Try to access DNS node which cloudflared created.

**Comment by tsakmas** [comment]
same problem for me for the last 3 hours or so. i dont know if there is a problem with the addon or cloudflare itself.

**Comment by MartinKuhl** [comment]
I have another server which uses the official cloudflare docker image and there I have the same issues.

**Comment by MartinKuhl** [comment]
my issue I forgot to renew my tk-domains.
