### ISSUE TITLE
Cloudflare blocks access from my phone

### ISSUE THREAD

**Issue by Arytmia** [brenner-tobias/addon-cloudflared#539]
### The problem

Hey, I have a bit of a strange problem.
I live on the border of two countries, I live in one, work in the other.
I very often connect to HA via wifi (locally), at work I use a domain on .xyz to connect by tunnel, via roaming.

Yesterday everything worked fine, I had access to the HA server all day. At home I used wifi, it was also ok.
This morning logging in from work, my phone could not connect to the server. The page was throwing up
 Unable to fetch auth providers. https://*censored*.xyz/lovelace?auth_callback=1, locking up on the Initalizing screen.

Connecting through a hotspot from a business phone (overseas, that is, not using roaming), the problem goes away immediately, I can connect to the HA server normally.

It seems as if using roaming on my phone is somehow blocking me through Cloudflare. 

What is even stranger is that if I perform the following steps -. 
1. connect via roaming (error)
2. connecting via hotspot (success)
3. entering lovelace, viewing dashboard (success)
4. disconnecting from the hotspot
5. the Home Assistant continues to work for a few minutes, then gets blocked again. Only reconnecting to the hotspot helps.

I suspect some kind of Cloudflare security bug, but I couldn't find anyone with a similar error.

I have default settings, I only added a firewall rule blocking access from outside Poland and Germany (but the error was occurring even before this rule).

### What version of Cloudflared has the issue?

4.2.12

### What type of installation are you running?

Home Assistant Supervised

### Add-on YAML Configuration

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```

### Anything in the logs that might be useful for us?

```txt
Nothing related
```

### Steps to reproduce the issue

1. connect via roaming (error)
2. connecting via hotspot (success)
3. entering lovelace, viewing dashboard (success)
4. disconnecting from the hotspot
5. the Home Assistant continues to work for a few minutes, then gets blocked again. Only reconnecting to the hotspot helps

**Comment by brenner-tobias** [comment]
Thanks for raising this. Did you set-up any kind of firewall rules?
Anyways, since this is nothing specific to this add-on but a general Cloudflare / Tunnel topic, I suggest you post this in the Cloudflare Community, which is very active and has the proper experts to help.

**Comment by Arytmia** [comment]
Seems to be solved.
For future users - on Xiaomi phones u must set private DNS. one.one.one.one (Cloudflare) works for me well.
