### ISSUE TITLE
QUIC connection failed

### ISSUE THREAD

**Issue by Vladx71** [brenner-tobias/addon-cloudflared#553]
### The problem

I'm not sure if this is an issue of the addon or the issue of my local set-up, but after searching for a solution I decided to put it here. Feel free to close it of it is totally offtopic :)

After configuring the addon I'm getting these errors in the log
`2024-01-01T12:45:15Z ERR Failed to create new quic connection error="failed to dial to edge with quic: CRYPTO_ERROR 0x178 (remote): tls: no application protocol" connIndex=0 event=0`

Checked my FW config (Fortigate) and QUIC is allowed. I also can connect to CF from HA
` ~ nc -vv 198.41.192.37 7844
198.41.192.37 (198.41.192.37:7844) open`

So, I suppose this is some kind of issue with the IPS (Telekom) maybe they are blocking QUIC

Fortunately CFD addon falls back to http2 after a few minutes, so the connection is working. So, if there is no other way to fix this, it would be great if force-http2 can be configured from the addon :) 

### What version of Cloudflared has the issue?

4.2.12

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: xxxx
additional_hosts:
  - hostname: xxxx
    service: https://192.168.1.100:4444
post_quantum: false
```

### Anything in the logs that might be useful for us?

```txt
2024-01-01T12:45:15Z ERR Failed to create new quic connection error="failed to dial to edge with quic: CRYPTO_ERROR 0x178 (remote): tls: no application protocol" connIndex=0 event=0
```

### Steps to reproduce the issue

install addon
configure tunnel
start addon

**Comment by brenner-tobias** [comment]
Thanks for raising this. In order for you to have the full control of the tunnel, I suggest to switch to a [remote managed tunnel](https://github.com/brenner-tobias/addon-cloudflared/wiki/How-tos#how-to-configure-remote-tunnels). 
Otherwise this does feel like an issue with your set-up, so feel free to play around with some options in the Zero Trust Dashboard with the remote tunnel

**Comment by Vladx71** [comment]
Hi,

I agree this is something with my local setup (probably some strange NAT
issue with my ISP), but it would be great if you can include a simple
switch to force using of http2 instead of QUIC for similar cases. I don't
think it is a very big effort :) As far as I know there is a command line
switch for cloudflared to force specific protocol

Thanks
L:
