### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by xibix-fp** [brenner-tobias/addon-cloudflared#555]
### The problem

Currently everything works as expected. My tunnel is established and works very well. But I have seen, that the tunnel is forwarding http (port 80), as well as https (port 443) to my homeassistant instance in my network. I would have expected an http to https rewrite, as the homeassistant locally only listens on port 443.
Is there maybe anything I am missing in my cloudflared configuration or in Cloudflare?

### What version of Cloudflared has the issue?

4.2.12

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Setup the cloudflared addon as per documentation. The domain that is being used, is a subdomain (ha.xxx.de). No additional configuration is made.

**Comment by brenner-tobias** [comment]
You can enable Always use https by following [this tutorial](https://developers.cloudflare.com/ssl/edge-certificates/additional-options/always-use-https/) (which I have).

**Comment by xibix-fp** [comment]
Perfect! Many thanks! Exactly what I was looking for.
