### ISSUE TITLE
Unable to start Cloudflared 5.0.0

### ISSUE THREAD

**Issue by Waterford-House** [brenner-tobias/addon-cloudflared#558]
### The problem

Since updating to v5.0.0 the Cloudflared add on had not been able to start successfully.  Log file indicates command not found. Uninstall and reinstall the add on has not helped.

### What version of Cloudflared has the issue?

5.0.0

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: *******.co.uk
additional_hosts: []
```

### Anything in the logs that might be useful for us?

```txt
/usr/bin/bashio: line 18: dirname: command not found
s6-rc: warning: unable to start service base-addon-banner: command exited 127
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

### Steps to reproduce the issue

Click 'Start' on Cloudflared Add On

### Additional information

Domain is registered with GoDaddy, and HA OS is running on an RPi4.

Many thanks

**Comment by xF3d33** [comment]
same here. sometimes ha lets me start the addon, but once i try to connect from the external url it crashes. i didn't update to the latest ha core version. i'm on 2023.12.4

**Comment by elcajon** [comment]
The command mentioned in the error message is definitely included. Also, no logics or dependencies have changed with the last update of the add-on. The add-on is based on the base image of the HA Community add-ons. Do they all work for you? For example, the SSH or VS Code add-on? What does your HA setup generally look like (OS or supervised installation)? As this is probably an isolated case, it will be difficult to narrow down the error without as much information as possible.

**Comment by elcajon** [comment]
> same here. sometimes ha lets me start the addon, but once i try to connect from the external url it crashes. i didn't update to the latest ha core version. i'm on 2023.12.4

Does the same error message appear or is it something completely different?

**Comment by xF3d33** [comment]
> > same here. sometimes ha lets me start the addon, but once i try to connect from the external url it crashes. i didn't update to the latest ha core version. i'm on 2023.12.4
> 
> Does the same error message appear or is it something completely different?

i don't know, i dont get any log in the logs page of the addon, only this in the ha general logs
![image](https://github.com/brenner-tobias/addon-cloudflared/assets/67204462/8873be8c-be0c-4df8-bc7d-c89092bdb256)
