### ISSUE TITLE
Update cloudflare/cloudflared to v2024.1.3 broke the tunnel

### ISSUE THREAD

**Issue by laptopology** [brenner-tobias/addon-cloudflared#576]
### The problem

403: Forbidden

### What version of Cloudflared has the issue?

5.0.2

### What was the last working version of Cloudflared?

5.0.1

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

update to the latest version

**Comment by elcajon** [comment]
The information provided is definitely not sufficient to find and rectify a possible issue.

**Comment by laptopology** [comment]
update bot did it again!

Maybe this will help: https://github.com/cloudflare/cloudflared/issues/1161
