### ISSUE TITLE
 Include the "path" option for additional hosts

### ISSUE THREAD

**Issue by INPoppoRTUNE** [brenner-tobias/addon-cloudflared#582]
### The problem

I'd like to have the option , as for #34, to define a path for the subdomain to link to:

```
additional_hosts:
  - hostname: example.example.com
    service: http://localhost:XXXX/path/to/stuff/
```

or

```
additional_hosts:
  - hostname: example.example.com
    service: http://localhost:XXXX
        path: /path/to/stuff/
```

### What version of Cloudflared has the issue?

5.1.1

### What was the last working version of Cloudflared?

None

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
Validating rules from /tmp/config.json
Validation failed: http://localhost:XXXX/path/to/stuff/ is an invalid address, ingress rules don't support proxying to a different path on the origin service. The path will be the same as the eyeball request's path
[18:43:29] FATAL: Validation of Config failed, please check the logs above.
```

### Steps to reproduce the issue

Add a path to the localhost address.

**Comment by elcajon** [comment]
It is best to use the [remote managed tunnel](https://github.com/brenner-tobias/addon-cloudflared/wiki/How-tos#how-to-configure-remote-tunnels) configuration for the use case you mentioned. For maintenance reasons, we try to keep the add-on options as compact as possible.

**Comment by INPoppoRTUNE** [comment]
The `service` field present at 7:
![](https://github.com/brenner-tobias/addon-cloudflared/raw/main/docs/images/4.png)
won't allow me to set a http://localhost:port **/path/to/something**, but only a ingress rule at root level, which is already possible from the plugin configuration page.

Am I missing something?

**Comment by INPoppoRTUNE** [comment]
> It is best to use the [remote managed tunnel](https://github.com/brenner-tobias/addon-cloudflared/wiki/How-tos#how-to-configure-remote-tunnels) configuration for the use case you mentioned.

The `service` field present at 7:
![](https://github.com/brenner-tobias/addon-cloudflared/raw/main/docs/images/4.png)
won't allow me to set a http://localhost:port **/path/to/something**, but only a ingress rule at root level, which is already possible from the plugin configuration page.

Am I missing something?

**Comment by elcajon** [comment]
Sorry, I misunderstood. This is not possible because it was not implemented upstream https://github.com/cloudflare/cloudflared/issues/563
