### ISSUE TITLE
Incorrect grammar in configuration

### ISSUE THREAD

**Issue by dnedeltchev** [brenner-tobias/addon-cloudflared#588]
### The problem

Incorrect grammar in configuration.
![Screenshot_20240205_230342_Home Assistant](https://github.com/brenner-tobias/addon-cloudflared/assets/60453167/d9c355a1-e398-49bd-a28a-8932e8695830)
It should read either
This also restricts
Or
This will also restrict

### What version of Cloudflared has the issue?

5.1.2

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Just a grammar error.

**Comment by elcajon** [comment]
Thanks for the suggestion! If iyou find anything else that is unclear/incorrect, please let us know.
