### ISSUE TITLE
Connection errors with Freenom issued domains

### ISSUE THREAD

**Issue by roydestroy** [brenner-tobias/addon-cloudflared#591]
### The problem

For some reason accessing HA remotely via the mobile app is fine. Trying to access from a computer using a web browser either gives a "Cannot connect to server" or an authentication error like this "This site can’t be reachedThe webpage at https://***/auth/authorize?response_type=code&redirect_uri=https%3A%2F%2F***f%2F%3Fauth_callback%3D1&client_id=https%3A%2F%2F***%2F&state=eyJoYXNzVXJsIjoiaHR0cHM6Ly9ibWtob21lLmNmIiwiY2xpZW50SWQiOiJodHRwczovL2Jta2hvbWUuY2YvIn0%3D might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED

### What version of Cloudflared has the issue?

5.1.2

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Trying to connnect remotely to HA using a web browser

**Comment by jasonlaguidice** [comment]
+1 same thing, this is currently broken.

Addon log does not report any incoming connections when attempting to access. Cloudflare dashboard reports tunnel is running and healthy.

Addon broke today on 5.1.1 and updating to 5.1.2 did not fix the problem.

I am running HA OS in a Proxmox LXC

Addon configuration only has the external hostname entered.

Connectivity does not work on any browser or app which uses the tunnel.

**Comment by TimiT-8** [comment]
+1 Same here for me. Suddenly stopped working. Looks like there was a issue with cloudflare dns load balancers, but they already implemented their fix and it's still broken...

**Comment by FeromonDE** [comment]
+1 Same here.

**Comment by TimiT-8** [comment]
What's the registrar you guys use? I got my domain from freenom and it looks like all their domains switched from active to pending... Looks like that's the reason why i cant access it anymore

**Comment by FeromonDE** [comment]
> What's the registrar you guys use? I got my domain from freenom and it looks like all their domains switched from active to pending... Looks like that's the reason why i cant access it anymore

Freenom too.

**Comment by 1nfinity84** [comment]
Freenom sadly.

**Comment by 1nfinity84** [comment]
Does pending mean domains are done for? Or is it just the dns servers are not reachable?

**Comment by H0d0rKF** [comment]
+1 Same her using Freenom but in my case the domain is shown acitv. Also no Errors in the CloudFlared Log. Problems with 5.1.1 and also after update to 5.1.2

**Comment by 1nfinity84** [comment]
Mine no longer has any DNS records. You might wanna lookup yours.
https://dnschecker.org/

**Comment by th9cb23** [comment]
+1 same issue here with .cf and .ovh domains

**Comment by goofy1988** [comment]
Same here, no access. tk domain from freenom. So freenom is the issue and not cloudflare?

**Comment by ededcck** [comment]
+1 same issue here with .tk domains

**Comment by ballakers** [comment]
> What's the registrar you guys use? I got my domain from freenom and it looks like all their domains switched from active to pending... Looks like that's the reason why i cant access it anymore

Yup I am on a .gq from freenom and also saw my domain says pending (guess it used to say active).  I could get the app to work remotely on and off but guessing that's from caching etc - I am far from an expert but what were the chances I was messing with my Cloudflare security settings the day before this happened, talk about a co-incidence.

**Comment by Helmaaar** [comment]
+1 .gq domain from freenom

**Comment by jasonlaguidice** [comment]
Adding this as found - seems as if others here are correct it's a freenom problem. Freenom is speculated to be down (for good)?

https://www.reddit.com/r/freenom/comments/1akf1cv/every_domain_is_now_down/

**Comment by Larosen** [comment]
Same issue here. But I can confirm, that Freenom is the cause and not this Add-On. I switched to another domain from netcup and now everything is fine again. I guess this issue can be closed 👍🏼

**Comment by jasonlaguidice** [comment]
Adding +1 as well - I migrated off the .tk domain and the addon works properly.

**Comment by roydestroy** [comment]
Guys I think this issue can even be closed. It is a problem of Freenom. I personally bought a new domain name from cloudflared and migrated and everyting is working fine.

**Comment by elcajon** [comment]
We'll leave the issue open for a few more days in case more Freenom users find their way here. Thanks for the troubleshooting. 👍🏼

**Comment by brenner-tobias** [comment]
Agreed, let's add a sentence in the main documentation as well as in the Wiki in the area about the domain name.

**Comment by 1nfinity84** [comment]
Hello, 
Tobias and elcajon - thanks for your work on the addon, safe to say it's not aproblem with it! Thank you!

To those who were affected - moving is very easy, if you purchase domain in your cloudflare panel. Simply just buy domain and then go to the old one, copy the cname record and uncheck the "proxied" switch.

Go to the new one and insert the cname (the loooong as string) add turn on proxied. 

Go to the addon and change the hostname, done.

(now you need to change the adress on your devices, phones, tablets...)

**Comment by oyvindhauge** [comment]
Thanks to everyone helping to solve the issue, and to @1nfinity84 for the simple how-to.

For anyone who are stuck. I had to delete the CNAME record for the *.tk-domain before it worked for me. It could be a coincidence, but it did not work for me when I just disabled "proxied".
