### ISSUE TITLE
tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by undee123** [brenner-tobias/addon-cloudflared#593]
### The problem

Followed the documentation to create a local tunnel, but after authorizing the domain in cloudflare the add-on stops with the error "ls: failed to verify certificate: x509: certificate signed by unknown authority".

### What version of Cloudflared has the issue?

5.1.2

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```

### Anything in the logs that might be useful for us?

```txt
Please open the following URL and log in with your Cloudflare account:

https://dash.cloudflare.com/argotunnel?aud=&callback=https%3A%2F%2Flogin.cloudflareaccess.org%2FFh9LYqMTd9U3JXPngXHh38YyR6k6YAwpseFE9GGb6zQ%3D

Leave cloudflared running to download the cert automatically.
Failed to write the certificate due to the following error:
Get "https://login.cloudflareaccess.org/Fh9LYqMTd9U3JXPngXHh38YyR6k6YAwpseFE9GGb6zQ=": tls: failed to verify certificate: x509: certificate signed by unknown authority

Your browser will download the certificate instead. You will have to manually
copy it to the following path:

/root/.cloudflared/cert.pem
Get "https://login.cloudflareaccess.org/Fh9LYqMTd9U3JXPngXHh38YyR6k6YAwpseFE9GGb6zQ=": tls: failed to verify certificate: x509: certificate signed by unknown authority
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

### Steps to reproduce the issue

created account on cloudflare.com
added cloudflare DNS to my domain name
waited 24 hours to become the DNS settings active

installed HA add-on
added http section in configuration yaml
restarted HAOS host

started  add-on
copied URL to authorize domain in cloudflare.com

add-on stopped with errors in log

### Additional information

already tried to uninstall and install the add-on a few times, didn't change anything.

**Comment by elcajon** [comment]
Does the error still occur like this? According to the error message, it seems to be a temporary problem on Cloudflare's side.

**Comment by undee123** [comment]
sorry for the late response, could not access my computers for a while. Problem is resolved, it seems indeed been a temporary cloudflare issue.

Thank you very much!
