### ISSUE TITLE
Can#t configure ADDON

### ISSUE THREAD

**Issue by mkurz0662** [brenner-tobias/addon-cloudflared#605]
### The problem

I have a new HA-Installation (2024.2.4)  and wanted to extend it with cloudflared.

After installation and restart of HA I'm not able to configure the addon.

Message: Fehler beim Speichern der Add-on Konfiguration, Invalid list for option 'additional_hosts' in Cloudflared (9074a9fa_cloudflared). Got {'external_hostname': '', 'additional_hosts': 'stargatenet.de'}

The folder : addons_config/9074a9fa_cloudflared  is empty and i can't find any config.yaml in the system or any other folder

### What version of Cloudflared has the issue?

5.1.4

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
there is no config.yaml on the system
```

### Anything in the logs that might be useful for us?

```txt
-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 5.1.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.2.4
 Home Assistant Supervisor: 2024.02.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[11:50:27] INFO: Checking add-on config...
[11:50:27] FATAL: Cannot run without tunnel_token, external_hostname, additional_hosts, catch_all_service or nginx_proxy_manager. Please set at least one of these add-on options.
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

### Steps to reproduce the issue

did a regular addon-installtion after adding repo : https://github.com/brenner-tobias/ha-addons  to addon-store.

**Comment by elcajon** [comment]
The error message looks like you have entered your domain stargatenet.de in additional_hosts. If you want to use the domain to access Home Assistant you have to enter it in external_hostname. If you want to use the domain for an additional host, please check the documentation again, as the entry is not correct. This is also what the error message says when saving the add-on configuration.

**Comment by mkurz0662** [comment]
Oh man. Next time i put my glasses on.  It works now!  THX
