### ISSUE TITLE
Cloudflared suddenly stopped working 

### ISSUE THREAD

**Issue by skrilla0** [brenner-tobias/addon-cloudflared#606]
### The problem

I've been running the Cloudflared Add-On tunnel for a long time (1.5 years+), and today suddenly it stopped working. Frustrated as no glaring configuration changes were made. I decided to recreate an entirely new tunnel, and the logs show it's connecting successfully to my origin. 

Double checked configuration yaml, and can confirm this is included: 
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.1.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5
```

When trying to login, getting the prompt, "Unable to connect to home assistant." 

### What version of Cloudflared has the issue?

5.1.4

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
[12:01:05] INFO: Connecting Cloudflare Tunnel...
2024-03-01T20:01:05Z INF Starting tunnel tunnelID=1b016700-de08-4e40-a962-32203992e2d0
2024-03-01T20:01:05Z INF Version 2024.2.1
2024-03-01T20:01:05Z INF GOOS: linux, GOVersion: go1.21.5, GoArch: arm64
2024-03-01T20:01:05Z INF Settings: map[config:/tmp/config.json cred-file:/data/tunnel.json credentials-file:/data/tunnel.json loglevel:info metrics:0.0.0.0:36500 no-autoupdate:true origincert:/data/cert.pem]
2024-03-01T20:01:05Z INF Generated Connector ID: 75974e64-cb4d-4e74-841d-0ce0f9c0d2c1
2024-03-01T20:01:05Z INF Initial protocol quic
2024-03-01T20:01:05Z INF ICMP proxy will use 172.30.33.5 as source for IPv4
2024-03-01T20:01:05Z INF ICMP proxy will use :: as source for IPv6
2024-03-01T20:01:05Z INF Starting metrics server on [::]:36500/metrics
2024-03-01T20:01:06Z INF Registered tunnel connection connIndex=0 connection=8844e7e7-f426-4073-a287-ce8d946702e9 event=0 ip=198.41.200.63 location=sjc08 protocol=quic
2024-03-01T20:01:06Z INF Registered tunnel connection connIndex=1 connection=9e3e4b4a-c3d5-4e3f-be78-ecfd395148ec event=0 ip=198.41.192.47 location=sjc01 protocol=quic
2024-03-01T20:01:07Z INF Registered tunnel connection connIndex=2 connection=39bf8807-2068-46b0-9bec-dc7b25e3c159 event=0 ip=198.41.200.43 location=sjc05 protocol=quic
2024-03-01T20:01:08Z INF Registered tunnel connection connIndex=3 connection=c6550ba7-3c52-4e26-a49c-de3336e52d56 event=0 ip=198.41.192.107 location=sjc06 protocol=quic
```

### Steps to reproduce the issue

- Recreated tunnel to make sure it's successfully connecting to origin server

**Comment by 1nfinity84** [comment]
Are you on a freenom domain by any chance?

**Comment by skrilla0** [comment]
> Same issue indeed. Have been playing around with it for 2 hours now but can't find a solution. The only hint I have is that's SSL related `net::ERR_SSL_UNRECOGNIZED_NAME_ALERT`
> 
> is what I can see in debug. Something seems to be off with the SSL certs here. I use a subdomain for bitwarden and had that setup in [NGINX Proxy Manager](https://github.com/hassio-addons/addon-nginx-proxy-manager) but suddenly things stopped working and I did an additional SSL cert in the proxy manager to secure access for the subdomain. On the root domain though that doesn't solve the issue since it's blocked to get another SSL cert for some reason (likely as lets encrypt can already find one for the main domain)
> 
> accessing your HA via http should get you to the login page at least. If yes, you got the same issue as me. It won't work to login as HA has HSTS enabled and will force SSL from there on which will fail due to cloudflared.
> 
> edit: in my case its a custom domain, nothing from freenom

Not sure if I'm experiencing a SSL issue. It's odd - I am able to access the initial login page from a Firefox browser, after entering login details and 2FA, it errors out, and get a login attempt failed. On Brave (Chromium), I can't even get the login page.

**Comment by Nicao** [comment]
> > Same issue indeed. Have been playing around with it for 2 hours now but can't find a solution. The only hint I have is that's SSL related `net::ERR_SSL_UNRECOGNIZED_NAME_ALERT`
> > is what I can see in debug. Something seems to be off with the SSL certs here. I use a subdomain for bitwarden and had that setup in [NGINX Proxy Manager](https://github.com/hassio-addons/addon-nginx-proxy-manager) but suddenly things stopped working and I did an additional SSL cert in the proxy manager to secure access for the subdomain. On the root domain though that doesn't solve the issue since it's blocked to get another SSL cert for some reason (likely as lets encrypt can already find one for the main domain)
> > accessing your HA via http should get you to the login page at least. If yes, you got the same issue as me. It won't work to login as HA has HSTS enabled and will force SSL from there on which will fail due to cloudflared.
> > edit: in my case its a custom domain, nothing from freenom
> 
> Not sure if I'm experiencing a SSL issue. It's odd - I am able to access the initial login page from a Firefox browser, after entering login details and 2FA, it errors out, and get a login attempt failed. On Brave (Chromium), I can't even get the login page.

Thats precisely the same error I do have, if you inspect your webpage and check the network log you should find what causes the issue. It seems like the same SSL issue

**Comment by brenner-tobias** [comment]
Is this sill happening? It feels like it might be related to some SSL hick-up or caching issue.
Can you try logging in via Incognito-Mode in one browser? Otherwise, my only suggestion would be to remove the domain from Cloudflare altogether and add it again (if feasible since this might be some work and comes with potentila downtime).

**Comment by skrilla0** [comment]
@brenner-tobias Thanks for suggesting this is a domain issue. Solved by using a different domain and now works again.
