### ISSUE TITLE
Alexa AWS Cloudfllare timeout

### ISSUE THREAD

**Issue by M4D1NG3R** [brenner-tobias/addon-cloudflared#611]
### The problem

Hello together,

I have Alexa configured via AWS & have been using the Cloudflared addon for some time now. But since a few days (round about after updating to HA 2023.3 & Cloudflared 5.1.5) the AWS Calls to my HA instance time out 90%  of the time.

When using Cloudflare DNS in proxy-mode I also get the timeout error. It seems like AWS & Cloudflare have some trouble working together currently.

The problem seems not be repeatable for everybody using the same setup, sine I found this post: [https://community.simon42.com/t/probleme-mit-alexa-geraete-nur-teilweise-ansprechbar/20672](https://community.simon42.com/t/probleme-mit-alexa-geraete-nur-teilweise-ansprechbar/20672)

here also, a thread in the HA forum: [https://community.home-assistant.io/t/alexa-aws-cloudfllare-timeout/701837](https://community.home-assistant.io/t/alexa-aws-cloudfllare-timeout/701837)

As a workaround, I now configured nginx & Cloudflare without proxy to get everything back up & running.

### What version of Cloudflared has the issue?

5.1.5

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

n/n

**Comment by VOSsec** [comment]
Unfortunately I have the same problem. When I restart the Cloudflare addon, access via Alexa works for a few seconds. As soon as I go into the Alexa app, I can only switch one device and then nothing works. The Lambda function spits out a positive debug at the beginning, as soon as I send a voice command via Alexa or via the app, the devices no longer respond... then the Lambda function spits out a failed log.😞

**What version of Cloudflared has the issue?**

5.1.5

**What was the last working version of Cloudflared?**

No response

**What type of installation are you running?**

Home Assistant Supervised Installed (2024.3)

**Add-on YAML Configuration**

No response

**Anything in the logs that might be useful for us?**

No response

**Steps to reproduce the issue**

n/n

**Additional information**

No response
<img width="1153" alt="Bildschirmfoto 2024-03-10 um 12 27 04" src="https://github.com/brenner-tobias/addon-cloudflared/assets/129999011/7abd82cb-663d-44f8-bdef-948218da5ae3"> 
<img width="1167" alt="Bildschirmfoto 2024-03-10 um 12 27 45" src="https://github.com/brenner-tobias/addon-cloudflared/assets/129999011/b84cbafa-34bc-453a-a72b-8b924f347573">

**Comment by elcajon** [comment]
I don't use Alexa, so I can only share a few ideas, but unfortunately I can't really help.
Also, it should be said that it is less a problem with the add-on and more with AWS and/or Cloudflare (or the Cloudflare tunnel).
In the past, I had also played around with the Alexa integration via AWS/Lambda.

What you can try to narrow down the error:

- Cloudflare part: Check the firewall log in the Cloudflare dashboard (open your Domain configuration, search the left menu for Security > Events, if I remember right I had to tweak with the security settings to get it working in the first place)
- Cloudflared tunnel part: Add `"--loglevel=debug"` as additional `run_parameters` to check the cloudflared tunnel log for errors related to Alexa (see [run_parameters documentation](https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#option-run_parameters))
- AWS part: I am not sure but maybe it is possible to get more connection logs to dig deeper into it on AWS side?
- Home Assistant part: The error message from the screenshot indicates an authentication error, I am no longer sure how this is integrated with HA but maybe there is something in the log here too. However, the fact that the command is executed correctly according to your statement speaks against this.

But as I said, I'm just poking around in the dark, sorry!
