### ISSUE TITLE
The WebSocket connection to mydomain failed

### ISSUE THREAD

**Issue by Triskae** [brenner-tobias/addon-cloudflared#628]
### The problem

I cannot connect to HA, since I have the following:  "The WebSocket connection to mydomain failed"
I tried to use this module in local mode, or in remote mode, and did not solved the problem.

### What version of Cloudflared has the issue?

5.1.8

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```

### Anything in the logs that might be useful for us?

```txt
Anything in the logs that are related to websocket failing or something.
```

### Steps to reproduce the issue

Install the extension, set the token to an existing tunnel. Configure a domain ha.mydomain.com, access it and it won't work.

### Additional information

Really strange, because I use this extension to also expose uptime, and the websocket for this service is working properly, only the HA websocket wont work.

**Comment by brenner-tobias** [comment]
Which Ports are you using? When you say "local mode" and "remote mode", do you mean locally within your network and externally of your network?
Can you please share your add-on config?

**Comment by Triskae** [comment]
Hello Thanks a lot for your answer.
In relation to local and remote mode, I was referring to the addon configuration. Here: [Local](https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#local-tunnel-add-on-setup-recommended) and [remote](https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#remote-tunnel-add-on-setup-advanced)
Here is my addon config:

```yaml
external_hostname: ""
additional_hosts: []
tunnel_token: >-
  my_cloudflare_token
```

Pretty basic config. Let me know if you need more details.

I also wanted to add a detail: The socket problem is not systematic, and seems to be a chrome/ium related problem, since in Firefox, I never had a problem ... I don't know if it help

**Comment by brenner-tobias** [comment]
Thanks. Which domain registrar are you using? The reason being, that we do have some issues with freenom...

**Comment by brenner-tobias** [comment]
so you are simply using HA in your browser and that is where the websocket error happens? In any case, I suggest that you first do a full un- and reinstall from the Add-On and if this does not help, backup your config and do a clean install of HA, if possible

**Comment by Triskae** [comment]
Thank you, I have to to try your solution.
