### ISSUE TITLE
s6-rc-compile: fatal

### ISSUE THREAD

**Issue by jurjenvanlaun** [brenner-tobias/addon-cloudflared#630]
### The problem

`s6-rc-compile: fatal: invalid /package/admin/s6-overlay-3.1.6.2/etc/s6-rc/sources/base-addon-banner/type: must be oneshot, longrun, or bundle`

Add on worked fine before, but now gives a compile error on start and cannot connect to ha anymore over cloudflared. I believe this happened after an update as i recently updated the addon.

### What version of Cloudflared has the issue?

5.1.9

### What was the last working version of Cloudflared?

5.1.6, i think

### What type of installation are you running?

Home Assistant OS on a raspberry Pi 4 Model B Rev 1.2. ARM64

### Add-on YAML Configuration

```yaml
external_hostname: ha.myhostname.com
additional_hosts: []
```

### Anything in the logs that might be useful for us?

```txt
s6-rc-compile: fatal: invalid /package/admin/s6-overlay-3.1.6.2/etc/s6-rc/sources/base-addon-banner/type: must be oneshot, longrun, or bundle
```

### Steps to reproduce the issue

Start add on, this log displays this error

### Additional information

Already tried uninstall and reinstall, as well as restarting the add on and ha core.

**Comment by jurjenvanlaun** [comment]
Already tried uninstall and install by the way.

**Comment by brenner-tobias** [comment]
with the latest update, we did not change anything on the services but the Cloudflared package version.
So this must be something else, my suggestion: Uninstall the add-on, do a full restart of HA and re-install it.
Let me know if this helped.

**Comment by jurjenvanlaun** [comment]
As stated in the issue, i already tried that. Just tried it again on fresh install after ha restart, same issue.
Looking back in connectivity logs the problem started 13/04 after an update. I update regularly, so i suspect it's an earlier update from either ha or the cloudlfared add on.

**Comment by jurjenvanlaun** [comment]
Are there any files i can manually delete? I think cloudflare itself is not the issue here given the compile error, and i can see the requests in cloudflare analytics.
Not sure where to start, also not familiar with s6.

**Comment by jurjenvanlaun** [comment]
I checked again, it started after an update to cloudflared 5.1.7

**Comment by jurjenvanlaun** [comment]
I think there is a misunderstanding, since the issue was closed. This issue isn't solved. I meant the problem started after 5.1.7.

**Comment by brenner-tobias** [comment]
yeah sorry, I thought it was resolved. Let me check

**Comment by brenner-tobias** [comment]
also from 5.1.7. to 5.1.9 the only difference really could be the new base image 15.0.8, where the only change was "Update OpenSSL to v3.1.4-r6", so really nothing that could cause this and I do not see issues in any of my installations.
@elcajon any idea?
@jurjenvanlaun can you please elaborate on your set-up (hardware vs. virtual solution, ...).

**Comment by jurjenvanlaun** [comment]
I'm running ha on hassos on a raspberry Pi 4 Model B Rev 1.2
Ha core version 2024.4.4 (issue also seen at 2024.4.1, not sure about earlier versions)
Supervisor version 2024.04.0
Not sure if the issue started with 5.1.7, is possible

**Comment by elcajon** [comment]
Sorry for the late response.
I have occasionally read something like this in the past in some hassio-addons repository issues. I don't remember a real solution. Most of the time it had to do with a corrupt Docker image DB. This doesn't seem to be a general problem, but occurs sporadically when there are internet / power outages during addon (docker image) updates.

I would recommend to create a full HA backup and rebuild the entire system with this backup.

**Comment by jurjenvanlaun** [comment]
Thanks for the response. Tried that already. Im not running home assistant itself in a docker setup as specified above by the way, but i run hassos. Did a full restore today again from a full backup, same error.

**Comment by jurjenvanlaun** [comment]
Not sure about i t not being a general issue. Perhaps thats true. Maybe i should file a big report with home assistant itself? However, it's only an issue on the cloudflared addon. Other addons update just fine. Updated another addon today which went fine.

**Comment by elcajon** [comment]
HAOS uses Docker internally. If you simply try to restore a backup, the existing data will be overwritten. But that won't clean up the Docker storage.
My suggestion would be to reset the hardware installation: https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-operating-system
--> In other words, flash the used SD/SSD again with a clean image, after the re-import the HA backup during the initial HA setup screen.

**Comment by jurjenvanlaun** [comment]
That did the trick. Thanks for pointing in the right direction, very weird error... Everything working as expected again.

**Comment by jurjenvanlaun** [comment]
Closing issue as it is resolved
