### ISSUE TITLE
Error after backup restore

### ISSUE THREAD

**Issue by deanfourie1** [brenner-tobias/addon-cloudflared#632]
### The problem

When starting and viewing logs in Cloudflared, I get the following error

`Failed to get add-on logs, No systemd-journal-gatewayd Unix socket available`

### What version of Cloudflared has the issue?

5.1.9

### What was the last working version of Cloudflared?

5.1.9

### What type of installation are you running?

Home Assistant Supervised

### Add-on YAML Configuration

```yaml
not relevant
```

### Anything in the logs that might be useful for us?

```txt
From the add on logs.

`Failed to get add-on logs, No systemd-journal-gatewayd Unix socket available`
```

### Steps to reproduce the issue

just restored the entire Proxmox VM from a backup using Proxmox Backup Server.

**Comment by elcajon** [comment]
This is an error that is more likely to be addressed to the supervisor / host. From an add-on perspective, there is nothing we can do. However, I assume that the error occurs due to the supervised installation type and the underlying host OS.

**Comment by deanfourie1** [comment]
Yea ok sorry this is a HA issue and is now resolved. Thanks
