### ISSUE TITLE
Multiple Hass Cloudflared Tunnels on the same domain name

### ISSUE THREAD

**Issue by Sjoerd** [brenner-tobias/addon-cloudflared#643]
### The problem

Hello,

I'm running a Hass instance for my parents and myself, but it's impossible to run them on the same domain name:

![image](https://github.com/brenner-tobias/addon-cloudflared/assets/19862992/a0fe46be-8ac3-46e7-978f-4af87ef00a03)

I don't want to delete the other instance of Cloudflared, and I would like to host them on the same domainname. It would be nice to have an option in the configuration to change the instance name from "homeassistant" to "homeassistant2" or "homeassistant[Location]". 

### What version of Cloudflared has the issue?

5.1.10

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
n/a
```

### Anything in the logs that might be useful for us?

```txt
n/a
```

### Steps to reproduce the issue

- Create a Hass VM
- Install the cloudflared add on
- Follow the installation steps
- Repeat

**Comment by elcajon** [comment]
The requested option is already available. 😉 
https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#option-tunnel_name

**Comment by Sjoerd** [comment]
> The requested option is already available. 😉 https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#option-tunnel_name

Whoops, my bad.
Thank you :)
