### ISSUE TITLE
Empty records for domain

### ISSUE THREAD

**Issue by emilleszczak2** [brenner-tobias/addon-cloudflared#650]
### The problem

I tried to configure Cloudflared Add-On. When I put token and confirmed, I received the domain but on the next page records were missing.

What going on?

### What version of Cloudflared has the issue?

latest

### What type of installation are you running?

Home Assistant Supervised

### Steps to reproduce the issue

1. Run Cloudflared configuration
2. Put a token and confirm
3. Select a domain
4. Empty records list

### Additional information

![Screenshot 2024-06-06 at 15 23 40](https://github.com/brenner-tobias/addon-cloudflared/assets/2837751/f1d1ffca-9b2a-4f76-8e7d-9900da84babc)
![Screenshot 2024-06-06 at 15 24 25](https://github.com/brenner-tobias/addon-cloudflared/assets/2837751/2e54c3a0-9454-49af-96af-60a2eef4695e)

_No response_

**Comment by brenner-tobias** [comment]
To confirm: You are using the Cloudflare Zero Trust Dashboard to create a remote managed tunnel, correct? If so, did you follow this description and where exactly in the process do the errors occur? Also, it would be helpful to translate the error messages in English for us to understand.
Thanks

**Comment by emilleszczak2** [comment]
Translation:
1. Choose zone to update
2. Choose records to update

There is no error message, just empty list of records.

I used guide to configure Zero Trust tunnel. Now i have no configuration in portal, clear it.

**Comment by elcajon** [comment]
The error does not come from the add-on but from the [Cloudflare integration](https://www.home-assistant.io/integrations/cloudflare). The integration is something different than the Cloudflare service provided by this add-on.

**Comment by emilleszczak2** [comment]
@elcajon thank you. I will post it on the integration page.
