### ISSUE TITLE
400: Bad Request

### ISSUE THREAD

**Issue by thomasf1** [brenner-tobias/addon-cloudflared#652]
### The problem

The tunnel sets up successfully and HA works locally, but when accessed via the Cloudflare domain, there is an 400: Bad Request error.

Not quite sure how best to debug it. Tested it via browser and mobile.

### What version of Cloudflared has the issue?

5.1.11

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

It´s a new install. Install the add-on, configure the domain, authorize cloudflare, 400 error

**Comment by elcajon** [comment]
Please take a look at the documentation under the following links
https://github.com/brenner-tobias/addon-cloudflared/wiki/Troubleshooting#400-bad-request-error
https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#home-assistant-configuration

**Comment by thomasf1** [comment]
Thanks! :)

Sorry, must have missed that...
