### ISSUE TITLE
HA app stops working after login token expiry

### ISSUE THREAD

**Issue by eshroom** [brenner-tobias/addon-cloudflared#654]
### The problem

I can set up cloudflared access via android app without any issues and use it until ybr login token expires. Once this happens the HA app throws an error and directs me to mobile chrome where dozens of HA attempted login pages are opened. No way to access HA via the app except to delete and reinstall.

Browser access is fine and when the token expires simply asks me to re authenticate with GitHub login.

### What version of Cloudflared has the issue?

5.1.11

### What was the last working version of Cloudflared?

5.1.11

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Simply login via app and wait for Cloudflare/github authentication to expire.

**Comment by brenner-tobias** [comment]
The additional authentication with GitHub or other providers is a known limitation with the Android-App, which unfortunately seems not to be desired by the dev team of the app, e.g. see this [PR](https://github.com/home-assistant/android/pull/3510) , [issue 1](https://github.com/home-assistant/android/issues/3205) or [issue 2](https://github.com/home-assistant/android/issues/2650).
You can try to follow this [explanation](https://community.home-assistant.io/t/home-assistant-app-through-cloudflare-tunnel/709951/13), but apart from that, the only solution is not to use an additional authentication provider.
Sorry that we cannot be of further help.

**Comment by pradumnk-mahanta** [comment]
> ### The problem
> I can set up cloudflared access via android app without any issues and use it until ybr login token expires. Once this happens the HA app throws an error and directs me to mobile chrome where dozens of HA attempted login pages are opened. No way to access HA via the app except to delete and reinstall.
> 
> Browser access is fine and when the token expires simply asks me to re authenticate with GitHub login.
> 
> ### What version of Cloudflared has the issue?
> 5.1.11
> 
> ### What was the last working version of Cloudflared?
> 5.1.11
> 
> ### What type of installation are you running?
> Home Assistant OS
> 
> ### Add-on YAML Configuration
> _No response_
> 
> ### Anything in the logs that might be useful for us?
> _No response_
> 
> ### Steps to reproduce the issue
> Simply login via app and wait for Cloudflare/github authentication to expire.
> 
> ### Additional information
> _No response_

Hi @eshroom,

You can also set up the Mobile Device to use the Client Certificate instead of using the Login Method. That way the Certificate lies on your device and Home Assistant App uses it for the communication, no third-party login required.
