### ISSUE TITLE
Changes to Additional Hosts does not delete them from Cloudflare

### ISSUE THREAD

**Issue by michaelblight** [brenner-tobias/addon-cloudflared#655]
### The problem

It would be good to have some documentation on how to remove/edit the addon properly. Initially I wanted to move some Additional Hosts to a separate Cloudfare tunnel and Cloudflared instance. After I removed them from the addon, they couldn't be added to the other tunnel because they were still defined at Cloudflare for the homeassistant tunnel. I thought uninstalling the addon would clean it up, but it still left everything there. I found I had to delete all the subdomain CNAMEs and the homeassistant tunnel on Cloudflare (I didn't delete the main domain CNAME). When I re-authorised the addon, it correctly set it up and started. But I'm not sure if this is the right approach.

### What version of Cloudflared has the issue?

5.1.11

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

You need to have a separate tunnel defined on Cloudflare and corresponding Cloudflared instance.

Then create an additional host in the addon and restart it. Then delete the additional host and restart the addon.

Then try and create that Public Host at Cloudflare for your other tunnel, and it doesn't work because the CNAMEs from the addon are still there, and presumably the additional host is still in the homeassistant tunnel.

**Comment by elcajon** [comment]
Form an add-on point of view we are not able to delete the DNS entries when the add-on is removed from your HA instance. But tbh all you need to do is to remove this DNS entries.
If you want easier automated configuration of your tunnel you can switch to the remote managed tunnel, so you can configure all Tunnel data from dash.cloudflare.com and just pass the tunnel token to this add-on (all other configuration options will be ignored in this case)
Let me know if this helps.

**Comment by michaelblight** [comment]
Fair enough if it can't be done automatically, which is why I was suggesting just updating the documentation to point out the extra steps that would need to be done on the Cloudflare side if additional hosts are removed or the addon is uninstalled.
