### ISSUE TITLE
zigbee2mqtt frontend using ingress not working

### ISSUE THREAD

**Issue by Dreaming-Codes** [brenner-tobias/addon-cloudflared#7]
**Describe the bug**
When i click on zigbee2mqtt i got this JS error in chrome console: `Uncaught SyntaxError: Unexpected end of input` and this in the extension log: `Unsolicited response received on idle HTTP channel starting with "0\r\n\r\n"; err=<nil>`

**To Reproduce**

1. Install zigbee2mqtt extension (repo: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt)
2. Install addon-cloudflared and configure it.
3. Visit home assistant throught the tunnel.
4. See error in extension log and in js console. 

**Expected behavior**
Zigbee2mqtt frontend load like when exposing port without using tunnel.

**Add-On / Home Assistant Information (please complete the following information):**

- Add-On Version: 0.1.8
- Supervisor Version: supervisor-2021.12.2
- Core Version: core-2021.12.7
- Operating System: Home Assistant OS 7.0
- Devices: virtualized on kvm

**Comment by Dreaming-Codes** [comment]
https://github.com/cloudflare/cloudflared/issues/446

**Comment by Dreaming-Codes** [comment]
Before investigating I would suggest updating cloudflared to 2021.12.4

**Comment by brenner-tobias** [comment]
Thanks for raising. I will soon release an update with the newest Cloudflared Version. After that, I will try to reproduce your issue.

**Comment by brenner-tobias** [comment]
I released the update yesterday, can you please check if anything changed?

**Comment by dflvunoooooo** [comment]
It is working now. 

I was wondering if there is a way to restrict access to specific add-ons for non local connections.

**Comment by brenner-tobias** [comment]
That's great to hear. Unfortunately, I am not sure if I get your point right, can you elaborate a little bit more on what you want to restrict?
Generally speaking, you can access everything via the Cloudflare Tunnel that you expose through it. If you do not add any additional_hosts and do not use the Nginxproxymanager option, then this is only HomeAssistant. That means, that you can access everything that is available via the HA UI. The Add-On only tunnels the HA-UI and cannot really differentiate between the different views or apps.

**Comment by dflvunoooooo** [comment]
I would like to restrict access to sertain add-ons, in particular zigbee2mqtt, for non local connections. But then I will try to do this via HA. Thanks for your quick reply!

**Comment by brenner-tobias** [comment]
Ok, got it. As mentioned, the add-on / tunnel cannot distinguish between the apps, since this is all going over the HA UI
