### ISSUE TITLE
Refactoring and security enhancement considerations

### ISSUE THREAD

**Issue by elcajon** [brenner-tobias/addon-cloudflared#71]
I recently thought about improving the security to make the add-on even more trustable. We could achieve this by removing the Hassio API manager role.

This would imply that we need to remove the checks mentioned below ( `bashio::addons.xxx` this one should be the only part where the manager role is needed). 
In my opinion we could omit this check. If the nginx add-on is installed everything works as expected, if not the host isn't reachable which will lead to a 404 error. Either way, this is the default behavior for services that are not reachable. 

https://github.com/brenner-tobias/addon-cloudflared/blob/ab348fb886d9fe953e95e98cd2763323aeb47942/cloudflared/rootfs/etc/cont-init.d/10-cloudflared-config.sh#L232

As described [here](https://developers.home-assistant.io/docs/add-ons/communication#network), I would set the following line to the hostname: `a0d7b954-nginxproxymanager`
https://github.com/brenner-tobias/addon-cloudflared/blob/ab348fb886d9fe953e95e98cd2763323aeb47942/cloudflared/rootfs/etc/cont-init.d/10-cloudflared-config.sh#L257

What do you think?

**Comment by brenner-tobias** [comment]
Great suggestion, I would love to get rid of the Manager role. I am not sure, that we can simply do that, because if we run the add-on with NGX support, we need to find the IP of it. Since we do not know the actual slug, we firstly need to find that (ending with some Github hash) and we can then get the IP of the NGX add-on, which can be any IP within the docker network. We are then using this IP in the Cloudflared config.
So the mentioned lines are not just checks but do actually get the IP we need for the config. I am not sure how to do it without the IP (or at leas the hostname, which should be the slug, which we store in `npm_name`.

Does that make sense?

**Comment by elcajon** [comment]
The IP isn't needed, the docker/hassio internal hostname will be sufficient for communication. From the [documentation](https://developers.home-assistant.io/docs/add-ons/communication/#network): 

> Names/aliases are used for communication inside Home Assistant. The name is generated using the following format: {REPO}_{SLUG}, e.g., local_xy or 3283fh_myaddon. In this example, {SLUG} is defined in an add-on's config.yaml file. You can use this name as the DNS name also, but you need replace any _ with - to have a valid hostname. If an add-on is installed locally, {REPO} will be local. If the add-on is installed from a Github repository, {REPO} is a hashed identifier generated from the GitHub repository's URL.

The hostname is defined as `{repo-hash}-{add-on-slug}`.

The `{repo-hash}` is unique for each GitHub repository and won't change. The [HA Community Repo](https://github.com/hassio-addons/repository) repo-hash is: `a0d7b954`.

The `{add-on-slug}` is defined in add-on's configuration.yaml. For Nginx [`nginxproxymanager`](https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/6b4bf543bf186251fd0e2b9a7ce1a33b6a3fd3a4/proxy-manager/config.yaml#L4).

So the hostname for nginx-proxy-manager is `a0d7b954-nginxproxymanager` - this hostname is accessible from within all Hass.io docker containers (including all add-ons). The hostname is also displayed in Supervisors Add-on info/overview site next to cpu/mem stats (if add-on is running).

Short digression: 
This also means, if you are using e.g. the add-on [(VS)Code-Server](https://github.com/hassio-addons/addon-vscode) or NodeRed, etc. You don't need to (docker-)forward any ports (which means opening ports for your internal HA Host IP)  to use the add-on UIs with Cloudflare created (sub)domains. E.g.:
```yaml
additional_hosts:
  - hostname: code.example.com
    service: http://a0d7b954-vscode:1337
```

**Comment by elcajon** [comment]
damn...

I forgot that the Warp extensions need manager API privileges. 

https://github.com/brenner-tobias/addon-cloudflared/blob/113dd43c28f9e3ed8eef5247dfcc0f455745eeec/cloudflared/rootfs/etc/cont-init.d/10-cloudflared-config.sh#L396

I think we've got three possibilities: 

1. Forget this issue and go back to daily business. 
2. Refactor discussed nginx related topics to reduce code.
3.  (2. and) remove automatic interface detection for creating warp routes and depend on currently optional `warp_routes` option. 

I would suggest to go with option 3, this will remove code complexity.

**Comment by brenner-tobias** [comment]
Thank for clarifying, I got the impression that the hash would change but this is perfect. I agree, let's go with option 3
