### ISSUE TITLE
Cannot add cloudfared to the store

### ISSUE THREAD

**Issue by Ashtray1807** [brenner-tobias/addon-cloudflared#714]
### The problem

Hello, 

I,m getting this error when trying to add the add-on to the store
![image](https://github.com/user-attachments/assets/a34422af-0d41-4e2d-a999-2224672341b1)

### What version of Cloudflared has the issue?

16.3.2

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Copy the git link and add it to the addon store in home assistant

**Comment by brenner-tobias** [comment]
This is the development repository, not the Add-On Repository for Home-Assistant. Please use [this repository](https://github.com/brenner-tobias/ha-addons), including the installation notes.
