### ISSUE TITLE
cannot access with CF

### ISSUE THREAD

**Issue by kadoshomerok** [brenner-tobias/addon-cloudflared#715]
### The problem

in the last several days i cannot access using CF from outside my network.
after installation there is a short time it is working (~3min)
i have uninstalled and reinstalled several times without success.
in CF side the tunnel is healthy and running.

core-2024.10.1
Home Assistant OS 13.1

### What version of Cloudflared has the issue?

5.1.21

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
2024-10-10T11:40:23Z ERR  error="Incoming request ended abruptly: context canceled" connIndex=3 event=1 ingressRule=0 originService=http://homeassistant:8123
2024-10-10T11:40:23Z ERR Request failed error="Incoming request ended abruptly: context canceled" connIndex=3 dest=https://<url>.xyz/frontend_latest/32665.EJNHHb2woKY.js event=0 ip=198.41.192.7 type=http
```

### Steps to reproduce the issue

it happens

**Comment by brenner-tobias** [comment]
A couple of questions to pinpoint the issue:

1. Did this work previously?
2. Do you also get other errors (e.g. failed to accept QUIC stream)?
3. Did you test another browser?
4. Are you using Cloudflare Zero Trust with an additional layer of authentication (e.g. Github)? If so, which one?
5. Did you set the option [post_quantum](https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#option-post_quantum) to true?

**Comment by kadoshomerok** [comment]
1. Worked perfectly until several days
2. No additional errors
3. Chrome, edge and androis apk
4. Only for HA
5. I didn't change its default state.... not sure what it is, will update later today

**Comment by kadoshomerok** [comment]
i have resolved it by setting it up in "advanced mode" - using tunnel token manually.
up and running!
