### ISSUE TITLE
Support HA Core?

### ISSUE THREAD

**Issue by ward0** [brenner-tobias/addon-cloudflared#723]
### The problem

![image](https://github.com/user-attachments/assets/29269317-cc7e-48cf-b389-c01ba25deb95)

### What version of Cloudflared has the issue?

2.0

### What type of installation are you running?

Other

### Steps to reproduce the issue

I can't install the addon.

**Comment by brenner-tobias** [comment]
What kind of HA set-up / installation are you running on what device?

**Comment by ward0** [comment]
> What kind of HA set-up / installation are you running on what device?

@brenner-tobias HA Core inside a Synology Docker container.

**Comment by brenner-tobias** [comment]
Unfortunately, we cannot support this set-up. If you are running synology Docker, I suggest to run another Docker container using the [official Cloudflared Container ](https://hub.docker.com/r/cloudflare/cloudflared)Image and set-up everything there. 
If you need support doing that, you can reach out to the [Cloudflare COmmunity. ](https://community.cloudflare.com/)
