### ISSUE TITLE
Error to add in Add-on Store

### ISSUE THREAD

**Issue by felipecrs** [brenner-tobias/addon-cloudflared#8]
Ok... I really don't know what's happening, but:

https://user-images.githubusercontent.com/29582865/148108183-7fa2533d-0fdf-493b-a3c0-d90bc0200a02.mp4

Am I missing something? Looking forward to use your add-on. Thank you!

**Comment by ngoldack** [comment]
I'm having the same issue

**Comment by brenner-tobias** [comment]
Thanks for raising the issue. This repository is the specific development repository for the add-on. There is a separate repository, which is formatted as a proper HomeAssistant Add-On Repository, which is including this add-on (and potentially others in the future). Please use this:

https://github.com/brenner-tobias/ha-addons

I acknowledge that this is pretty confusing and will think about a simpler solution.

Please open again if this does not help you.

**Comment by felipecrs** [comment]
A simple way to fix is to perhaps add a note about it in the README of this repo.

Thank you for pointing me at the right direction!
