### ISSUE TITLE
Upstream default protocol changed from http2 to quic

### ISSUE THREAD

**Issue by elcajon** [brenner-tobias/addon-cloudflared#86]
**Is your feature request related to a problem? Please describe.**

Home Assistant OS 7.6
since cloudflared version 2022.4.0, current add-on version 2022.4.1

The problem is OS related and can't be fixed from inside the add-on.

Log excerpt:
```
2022/04/29 18:30:50 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 58 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
```

See [issue](https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size) mentioned in log message.

**Additional context**

The default protocol for creating tunnels changed from `http2` to `quic` with cloudflared version 2022.4.0 [TUN-5992](https://github.com/cloudflare/cloudflared/blob/master/RELEASE_NOTES)

See [cloudflared service doc](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/arguments/#protocol) for further information. (Doc doesn't seem up to date as it still mentions `http2` as default value).

`quic` protocol will be the future according to the [developers](https://github.com/cloudflare/cloudflared/issues/513#issuecomment-975954272) (among others for UDP support).

**Describe alternatives you've considered**

For HA OS:
- Change default protocol to `http2` in services.d/run (wouldn't recommend that, though)
- We open a ticket in HA OS with a request to increase the value.
- Hint on how to change `sysctl -w net.core.rmem_max=2500000` (we can issue the command but it isn't persistent between reboots):
--> Workaround with [HA OS persistent UDEV rules](https://github.com/home-assistant/operating-system/blob/dev/Documentation/configuration.md#udev-rules) would be possible
--> `ACTION=="add", KERNEL=="sd*", RUN+="/sbin/sysctl -w net.core.rmem_max=2500000"`
This will change kernel parameter on every reboot when device with kernel name `sd*` eg. `sda`or `sdb` (which should be the name in default configurations) is connected. Works fine for me on Proxmox with KVM (.qcow2) image.

For HA Supervised installations: 
- create documentation for Supervised Installations: execute `sysctl -w net.core.rmem_max=2500000`

**Comment by brenner-tobias** [comment]
Thanks for raising. I have not yet seen any error like that in my logs, running the newest HA and the Edge release of this add-on. 
How is this affecting the connection?

**Comment by elcajon** [comment]
Interesting, what HA installation method and platform are you using?
So far I can't see any negative impact except for the error message. Presumably this will only lead to problems in the future when further UDP functionalities are implemented by Cloudflare.

**Comment by brenner-tobias** [comment]
I am running on a RPi4-64, Home Assistant OS 7.6, Supervisor Version: supervisor-2022.05.0. 
Also on my other system, running also on a Pi4 with the stable release of the add-on, there are no such logs.

**Comment by elcajon** [comment]
Then the problem refers only to some installation methods and not to all. Thus, I would close the issue for the time being until further feedback is received.

**Comment by shahrilamrias** [comment]
Hi guys, just installed the add-on on a new installation of HA OS and getting the quic warning immediately after cloudflared starts fetching the remote management config. 

>  Add-on version: 2.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.5.5
 Home Assistant Supervisor: 2022.05.3

**Comment by brenner-tobias** [comment]
I did change one of my installations to the managed tunnel and now I am also getting the error there, so I am reopening.

@elcajon let's discuss how to approach this

**Comment by elcajon** [comment]
I see only the following possibilities. For me the described workaround is still working pretty good

> For HA OS:
> 
> * Change default protocol to `http2` in services.d/run (wouldn't recommend that, though)
> * We open a ticket in HA OS with a request to increase the value.
> * Hint on how to change `sysctl -w net.core.rmem_max=2500000` (we can issue the command but it isn't persistent between reboots):
>   --> Workaround with [HA OS persistent UDEV rules](https://github.com/home-assistant/operating-system/blob/dev/Documentation/configuration.md#udev-rules) would be possible
>   --> `ACTION=="add", KERNEL=="sd*", RUN+="/sbin/sysctl -w net.core.rmem_max=2500000"`
>   This will change kernel parameter on every reboot when device with kernel name `sd*` eg. `sda`or `sdb` (which should be the name in default configurations) is connected. Works fine for me on Proxmox with KVM (.qcow2) image.
> 
> For HA Supervised installations:
> 
> * create documentation for Supervised Installations: execute `sysctl -w net.core.rmem_max=2500000`

**Comment by brenner-tobias** [comment]
Agreed, I opened an issue within the OS repo: https://github.com/home-assistant/operating-system/issues/1964

**Comment by michaelhart** [comment]
This is also impacting me with a fresh install of Home Assistant OS on macOS in Virtual Box. Running `sysctl -w net.core.rmem_max=2500000` produces no results, error: 
```
sysctl: error: 'net.core.rmem_max' is an unknown key
```
Any advice to unblock using this until it's properly fixed?

**Comment by elcajon** [comment]
You could try `sysctl -w kern.ipc.maxsockbuf=3014656`
From: https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size#bsd
Not sure if this works, didn't test it myself.

**Comment by elcajon** [comment]
> Similar result: `sysctl: error: 'kern/ipc/maxsockbuf' is an unknown key`

Just to be sure, did you try `kern.ipc.maxsockbuf` instead of `kern/ipc/maxsockbuf` as shown in your error message?

**Comment by michaelhart** [comment]
Yes, typed exactly. It was converted in the error message.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/1617102/172461924-5fdcc411-9384-4e6d-a6b3-d2ffe6a978ab.png">

**Comment by elcajon** [comment]
Did you try to execute the command from the HA SSH add-on?

**Comment by michaelhart** [comment]
Yes, that's where that screenshot is from (the "Terminal" menu on the left).  Addon: "Terminal & SSH" 9.4.0.

**Comment by elcajon** [comment]
Alright I get it, this command needs to be run from the HA operating system as the add-on didn't has the necessary host privileges.
Take a look here: https://developers.home-assistant.io/docs/operating-system/debugging/

**Comment by michaelhart** [comment]
Huge thanks @elcajon for including the alternate approach (`login` command at HA OS console -- because getting a USB drive into that VM would have been impossible given macOS's SPI blocking Virtual Box extensions).

I was able to add a file (which I learned must end in `.rules`) to `/etc/udev/rules.d` containing `ACTION=="add", KERNEL=="sd*", RUN+="/sbin/sysctl -w net.core.rmem_max=2500000"` and it cleared up the buffer size error. The other mistake I was making was using localhost:8123 instead of homeassistant:8123 to the tunnel created in Cloudflare. As soon as I updated that, it worked perfectly.

**Comment by elcajon** [comment]
[HA OS 8.2](https://github.com/home-assistant/operating-system/releases/tag/8.2) contains the necessary changes and is actually available as beta update. I guess it will be released pretty soon. I am running the stable version so I couldn't test it yet.

**Comment by shahrilamrias** [comment]
HAOS 8.2 stable has just been released and I can confirm that no more warning is being generated in the addon logs. 

Thank you everyone 😁

**Comment by brenner-tobias** [comment]
Some for me here, works like a charm. Thanks everyone!
