### ISSUE TITLE
Block certain substrings of a forwarded domain.

### ISSUE THREAD

**Issue by jaddel** [brenner-tobias/addon-cloudflared#97]
I currently use the following forward to expose my bitwarden addon to the web.

```
- hostname: bw.example.com
  service: https://addon_a0d7b954_bitwarden:7277
```
Would it be possible to for example block the following substring from being accessed by the web?
`https://bw.example.com/Admin`

**Comment by elcajon** [comment]
Hi @jaddel, this is indeed possible with Cloudflare but not part of this add-on.

1. Open [Cloudflare Zero Trust Dashboard](https://dash.teams.cloudflare.com)
2. Navigate to Access > Applications
3. Add a new application (type Self-hosted)
4. Configure the add-on and (if you want to be able to access the admin page) add/choose the correct identity provider(s).

Take a look [here](https://developers.cloudflare.com/cloudflare-one/applications/configure-apps/self-hosted-apps/) for further information.

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/52052494/168572277-9df9deef-bf55-4fe5-8be9-20cbfdf3a68e.png">

**Comment by jaddel** [comment]
This is awesome! Many thanks for the great explanation. :)
