### ISSUE TITLE
configuration.yaml

### ISSUE THREAD

**Issue by cvalcke958** [brenner-tobias/addon-cloudflared#98]
while the installation is simple enough (both HA and cloudflare), would be nice to provide an example of
the corresponding entries in the configuration.yaml file.

my 'minimal' version isn't working
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.50.16

**Comment by elcajon** [comment]
Take a Look here
https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#configurationyaml
